QUESTIONS = [
    # A.1 Safety
    ('A.1', 'A 1.2 kW amplifier power supply runs from the 230 V mains. Which plug fuse is appropriate?',
     ['3 A', '5 A', '13 A', '30 A'], 'C',
     '1200/230 ≈ 5.2 A; a 13 A fuse allows up to about 2990 W', '2 990 W'),
    ('A.1', 'Why should you never rely on bleeder resistors alone to discharge high-voltage capacitors?',
     ['They are a frequent point of failure', 'They increase the voltage', 'They are only fitted to valve receivers', 'They discharge too quickly'], 'A',
     'Bleeder resistors often fail; always use a shorting stick', 'frequent point of failure'),
    ('A.1', 'Keeping one hand behind your back when working on high voltages helps to:',
     ['Keep your balance', 'Avoid a current path from one hand, across your chest, to the other', 'Earth the equipment', 'Reduce RF exposure'], 'B',
     'Prevents a hand-to-hand path across the chest', 'across the chest'),
    ('A.1', 'You get RF burns from the metal case of your transceiver or microphone. A likely cause is:',
     ['The mains fuse is too small', 'The SWR is exactly 1:1', 'The antenna is too high',
      'Improperly earthed equipment carrying RF (e.g. common-mode current from the coax)'], 'D',
     'RF on improperly earthed equipment, often common-mode current', 'improperly earthed'),
    ('A.1', 'With a high-gain Yagi or dish antenna, particular care is needed to ensure that people cannot be:',
     ['Behind the reflector', 'Below the rotator', 'Directly in front of the beam at close range', 'In another room of the house'], 'C',
     'Fields are concentrated in front of directional antennas', 'in front of the beam'),
    # A.2 Interference and Immunity
    ('A.2', 'Electromagnetic compatibility (EMC) means:',
     ['Equipment that works only with the same brand',
      'The ability of equipment to work properly in its electromagnetic environment without causing intolerable disturbance to others',
      'Compatibility with the mains voltage', 'Connecting coax of the same impedance'], 'B',
     'Definition of EMC', 'Electromagnetic Compatibility'),
    ('A.2', 'Intermodulation is:',
     ['The mixing of two or more signals in a non-linear device, producing new, unwanted frequencies', 'Fading caused by multipath',
      'Distortion of the audio only', 'The modulation of a carrier by speech'], 'A',
     'Non-linear mixing creates intermodulation products', 'intermodulation'),
    ('A.2', 'For a ferrite ring to be effective as a common-mode choke at HF, it usually helps to:',
     ['Glue it to the transceiver', 'Use it only on the mains plug', 'Paint it', 'Pass several turns of the cable through the ring'], 'D',
     'Multiple turns increase the choking impedance', 'ferrite'),
    ('A.2', 'A receiver is overloaded by strong signals outside the band you are listening to. What may help?',
     ['A longer feeder', 'Turning up the AF gain', 'A band-pass filter at the receiver input (or an attenuator)', 'A higher-gain antenna'], 'C',
     'Front-end filtering keeps strong out-of-band signals out', 'band-pass filter'),
    # A.3 Theory
    ('A.3', 'A current of 0.5 A flows through a 220 Ω resistor. The voltage across it is:',
     ['440 V', '110 V', '220.5 V', '2.3 mV'], 'B',
     'V = IR = 0.5 × 220 = 110 V', ('Ohm’s law', 20, 23)),
    ('A.3', 'A signal has a wavelength of 2 m. Its frequency is about:',
     ['150 MHz', '15 MHz', '600 MHz', '1.5 MHz'], 'A',
     'f = 300/λ = 300/2 = 150 MHz', 'Wavelength and Frequency'),
    ('A.3', 'A loss of 10 dB corresponds to a power ratio of:',
     ['0.5', '0.25', '2', '0.1'], 'D',
     '−10 dB = one tenth', ('decibel', 116, 119)),
    ('A.3', 'Quantisation in an analogue-to-digital converter (ADC) means:',
     ['Taking samples at regular time intervals', 'Filtering the input', 'Rounding each sample to one of a finite set of digital values', 'Converting digital back to analogue'], 'C',
     'Quantisation maps each sample to a discrete level', 'quantisation'),
    # A.4 Components
    ('A.4', 'A tuned circuit resonant at 3.6 MHz has a Q of 100. Its bandwidth is about:',
     ['3.6 kHz', '36 kHz', '360 kHz', '100 kHz'], 'B',
     'BW = f/Q = 3600 kHz / 100 = 36 kHz', 'Q factor'),
    ('A.4', 'The circuit shown is a:',
     ['Low-pass filter', 'Band-stop filter', 'Band-pass filter', 'High-pass filter'], 'D',
     'Series C blocks low frequencies; shunt L shorts low frequencies to ground', 'high-pass', 'set12_q15'),
    ('A.4', 'A light-emitting diode (LED) is normally operated:',
     ['Reverse biased, with no resistor', 'Directly across the mains', 'Forward biased, with a series current-limiting resistor', 'Only on AC'], 'C',
     'LEDs need forward bias and current limiting', 'light-emitting'),
    # A.5 TX/RX
    ('A.5', 'In a superheterodyne receiver, rejection of the image frequency is mainly provided by:',
     ['Selective filtering before the mixer (RF stages)', 'The audio amplifier', 'The AGC', 'The S meter'], 'A',
     'The image must be removed before the mixer', 'image frequency'),
    ('A.5', 'Compared with FM, the duty cycle placed on a transmitter\'s power amplifier by CW is:',
     ['Higher — CW is a continuous carrier', 'Lower — the carrier is keyed on and off', 'Exactly the same', 'Zero'], 'B',
     'FM is 100% duty; CW is keyed', 'duty cycle'),
    ('A.5', 'In the receiver shown, block "X" feeds the product detector. When receiving CW or SSB, X is the:',
     ['Local oscillator for the first mixer', 'Squelch', 'Discriminator', 'Beat frequency oscillator (BFO)'], 'D',
     'The BFO/CIO feeds the product detector', 'Beat Frequency Oscillator', 'set12_q19'),
    ('A.5', 'In an FM receiver, the limiter:',
     ['Limits the audio volume', 'Limits the bandwidth to 3 kHz', 'Removes amplitude variations (noise) before the discriminator', 'Limits transmitter power'], 'C',
     'FM carries information in frequency, so amplitude noise is clipped', 'limiter'),
    # A.6 Antennas
    ('A.6', 'Common-mode current on a coaxial feeder flows:',
     ['Only on the inner conductor', 'On the outside surface of the braid', 'Only inside the dielectric', 'Only in the antenna'], 'B',
     'Common-mode current flows on the outside of the shield', ('common mode current', 214, 215)),
    ('A.6', 'A disadvantage of open-wire (parallel) feeder compared with coax is that it:',
     ['Has higher loss', 'Cannot handle high power', 'Is unbalanced', 'Must be kept away from metal objects and other conductors'], 'D',
     'Nearby conductors upset the balance of parallel lines', ('parallel lines', 209, 210)),
    ('A.6', 'The feed point impedance of a quarter-wave vertical with radials on the ground is roughly:',
     ['36 Ω', '300 Ω', '600 Ω', '2000 Ω'], 'A',
     'About half of a dipole\'s 73 Ω', 'Quarter-wave Vertical with Radials on the Ground'),
    ('A.6', 'To make a resonant half-wave dipole work on a lower frequency, it must be:',
     ['Shorter', 'Fed with higher power', 'Longer', 'Mounted vertically'], 'C',
     'Length is proportional to wavelength', ('Half-Wave Dipole', 231, 233)),
    # A.7 Propagation
    ('A.7', 'In the daytime ionosphere shown, which numbered layer mainly absorbs lower HF signals?',
     ['Layer 4', 'Layer 3', 'Layer 2', 'Layer 1'], 'D',
     'The lowest layer, the D layer, absorbs low HF in daytime', ('D layer', 259, 260), 'set12_q25'),
    ('A.7', 'The maximum usable frequency (MUF) on a given HF path is usually:',
     ['Higher in daytime than at night', 'Higher at night than in daytime', 'The same at all times', 'Below 1 MHz'], 'A',
     'Solar ionisation in daytime raises the MUF', 'Maximum Usable Frequency'),
    ('A.7', 'Reliable 2 m FM contacts over a few tens of kilometres normally use:',
     ['Sky wave via the F2 layer', 'Line-of-sight (space wave) propagation', 'EME', 'Ground wave over the sea only'], 'B',
     'VHF relies on line-of-sight propagation', 'Line-of-Sight Propagation'),
    ('A.7', 'During an auroral opening on 2 m, stations in Ireland usually point their beams:',
     ['South', 'Straight up', 'Northwards, towards the aurora', 'At the Moon'], 'C',
     'Signals scatter off the aurora to the north', 'auroral'),
    # A.8 Measurements
    ('A.8', 'To measure a 13.8 V DC supply on a multimeter with ranges 2 V, 20 V and 200 V DC, you should choose:',
     ['The 2 V range', 'The 200 mA range', 'The resistance range', 'The 20 V DC range'], 'D',
     'Choose the lowest range above the expected value', 'voltmeter'),
    ('A.8', 'An SWR meter shows 100 W forward and 0 W reflected power. The SWR is:',
     ['Infinite', '1:1', '2:1', '100:1'], 'B',
     'No reflected power = perfect match', 'SWR meter'),
    # B.1
    ('B.1', '"Sierra Papa Five Kilo X-ray" spells the call sign:',
     ['SP5KX', 'SB5KX', 'CP5KX', 'SP5QX'], 'A', 'S-P-5-K-X', 'Sierra'),
    # B.2
    ('B.2', '"QSY?" means:',
     ['Is my signal fading?', 'What is your location?', 'Shall I change frequency?', 'Who is calling me?'], 'C',
     'QSY? = shall I change frequency?', 'Shall I start transmitting on'),
    ('B.2', 'The operational abbreviation "TX" means:',
     ['Thanks', 'Telex', 'Text message', 'Transmitter'], 'D', 'TX = transmitter', 'Transmitter'),
    ('B.2', '"QRN" means you are bothered by:',
     ['Interference from other stations', 'Static or noise of natural (atmospheric) origin', 'Fading', 'A busy frequency'], 'B',
     'QRN = atmospherics', 'bothered by atmospherics'),
    # B.3
    ('B.3', 'Which of these is one of Ireland\'s Principal Emergency Services (PES)?',
     ['The Fire Service', 'The Irish Red Cross', 'Civil Defence', 'The Order of Malta'], 'A',
     'PES: Garda, Ambulance Service, Fire Service (and the Irish Coast Guard)', 'PRINCIPAL EMERGENCY SERVICES'),
    ('B.3', 'The Irish emergency centre of activity 14.300 MHz is in the:',
     ['40 m band', '17 m band', '20 m band', '15 m band'], 'C', '20 m = 14.000–14.350 MHz', 'Yes Yes 14.300'),
    ('B.3', 'You own a repeater but have no emergency communications training. What can you do?',
     ['Nothing — only trained operators can help', 'Pass emergency traffic yourself', 'Switch it off during emergencies',
      'Offer it to an approved emergency communications organisation such as AREN'], 'D',
     'You can make equipment available without passing traffic', 'make your equipment available'),
    # B.4
    ('B.4', 'A call sign such as EI9VAB is issued to:',
     ['A special event station', 'A licensed visitor from a non-CEPT country under a reciprocal agreement', 'A repeater', 'A club'], 'B',
     'Visitor call signs have V after the number', 'EI9VAB'),
    ('B.4', 'A German licensee (DL1ABC) visiting the Aran island of Inishmore under CEPT arrangements uses:',
     ['EJ/DL1ABC', 'EI/DL1ABC', 'DL1ABC/EJ', 'EJ1ABC'], 'A',
     'EJ/ for Irish offshore islands', 'Inishmore'),
    ('B.4', 'The national prefix for Romania is:',
     ['RO', 'YR', 'YO', 'RA'], 'C', 'Romania = YO', 'Romania'),
    # B.5
    ('B.5', 'Which band is allocated on a secondary basis in Ireland but still permits contests?',
     ['60 m', '30 m', '6 m', '17 m'], 'C',
     '6 m: secondary, 100 W, contests yes', '50.000–52.000'),
    ('B.5', 'Is maritime mobile operation permitted on the 2 m band?',
     ['No', 'Yes, at up to 10 W', 'Yes, at up to 400 W', 'Only in harbours'], 'B',
     '2 m permits /MM; the /MM limit is 10 W', '144.000–146.000'),
    ('B.5', 'In the IARU R1 80 m band plan, 3690 kHz is the:',
     ['Emergency centre of activity', 'CW QRP centre of activity', 'Digital voice centre of activity', 'SSB QRP centre of activity'], 'D',
     '3690 kHz = SSB QRP CoA', '3690 kHz'),
    ('B.5', 'In the simplified 80 m band plan, 3600–3650 kHz is:',
     ['All modes, SSB contest preferred', 'CW only', 'Beacons', 'Narrow-band digimodes only'], 'A',
     'All modes, SSB contest preferred', 'SSB contest preferred'),
    # B.6
    ('B.6', 'Conflicts between amateurs can arise mainly because:',
     ['ComReg assigns the same frequency to everyone', 'The radio spectrum is a space shared by everyone with their own interests and goals',
      'Band plans do not exist', 'Amateurs may only use one band'], 'B',
     'The spectrum is shared by all', 'shared by all'),
    ('B.6', 'Contesting aims to:',
     ['Make the longest possible QSOs', 'Test antennas only', 'Make many error-free, correctly logged contacts', 'Jam other stations'], 'C',
     'Many error-free logged contacts', 'error-free'),
    ('B.6', 'In written amateur communications, the usual greeting "73" means:',
     ['Best regards', 'Love and kisses', 'Goodbye forever', 'Thank you for the QSO'], 'A',
     '73 = best regards', 'stands for best regards'),
    # B.7
    ('B.7', 'The T in an RST report describes:',
     ['The time of the contact', 'The temperature', 'The transmitter power', 'The tone quality of a Morse or digital signal'], 'D',
     'T = tone (CW/digital)', 'TON E . Used only in Morse'),
    ('B.7', 'On HF, a "DX" station is usually one that is:',
     ['In the same town', 'On another continent', 'Using digital modes', 'Operating mobile'], 'B',
     'DX on HF = another continent', 'stations on another continent'),
    ('B.7', 'You call CQ DX and a station that is not DX for you answers. You should:',
     ['Ignore them', 'Tell them off', 'Be obliging: make a quick QSO and then call DX again', 'Report them'], 'C',
     'Be obliging and polite', 'be obliging'),
    ('B.7', 'From an operating point of view, during a contest the best practice is to identify:',
     ['At each QSO (not necessarily each over)', 'Never', 'Once per hour', 'Only at the end of the contest'], 'A',
     'Identify at each QSO', 'identify at each QSO'),
    ('B.7', 'The Wireless Telegraphy regulations make it illegal to cause harmful interference to other users, notably:',
     ['Other amateurs on CW', 'Broadcast listeners only', 'CB users', 'Radionavigation and radiocommunications services'], 'D',
     'Notably radionavigation and radiocommunications services', 'Radionavigation'),
    # B.8
    ('B.8', 'In ITU emission designators, the first letter G means:',
     ['Amplitude modulation', 'Frequency modulation', 'Phase modulation', 'Single sideband'], 'C', 'G = phase modulation', 'Phase modulation'),
    ('B.8', 'How many of the amateur bands in the exam syllabus are allocated on a secondary basis?',
     ['Four (5, 10, 50 and 70 MHz)', 'None', 'All of them', 'Two'], 'A', '5, 10, 50 and 70 MHz', 'Four of the amateur bands'),
    # B.9
    ('B.9', 'In most countries, a CEPT licence is treated as equivalent to:',
     ['A listening permit', 'The highest national amateur licence, subject to conditions', 'A CB licence', 'A broadcasting licence'], 'B',
     'Equivalent to the highest licence, with conditions', 'highest amateur station licence'),
    ('B.9', 'The national prefix for Estonia is:',
     ['EE', 'ET', 'YL', 'ES'], 'D', 'Estonia = ES', 'Estonia'),
    ('B.9', 'The national prefix for Slovakia is:',
     ['SK', 'OK', 'OM', 'S5'], 'C', 'Slovakia = OM', 'Slovakia'),
    # B.10
    ('B.10', 'Who issues Amateur Station Licences in Ireland?',
     ['ComReg', 'The IRTS', 'The Department of Communications', 'CEPT'], 'A', 'ComReg issues the licences', 'issues Amateur Station Licences'),
    ('B.10', 'Which of these needs a formal additional authorisation from ComReg?',
     ['Operating /M', 'Using CW', 'Logging in UTC', 'An Internet gateway or other automatic/remote station'], 'D',
     'Automatic or remote stations need authorisation', 'Internet gateway'),
    ('B.10', 'The logbook must record, for each day, the times in UTC of:',
     ['Every over', 'The first and last transmissions, and changes of band, mode or power', 'Only CQ calls', 'Meals'], 'B',
     'First/last transmissions and changes', 'first and last transmissions'),
]
