QUESTIONS = [
    # A.1 Safety
    ('A.1', 'What is the most common cause of fatal electrical accidents?',
     ['Ordinary 230 V mains circuits', '12 V vehicle batteries', 'RF from handheld radios', 'Static electricity'], 'A',
     'Ordinary 230 V circuits are the most common cause of fatal accidents', 'most common cause of fatal'),
    ('A.1', 'An RCD (or ELCB) cuts the power when:',
     ['The supply voltage drops below 200 V', 'The load draws more than 13 A',
      'The currents in the live and neutral conductors become unequal by its rated amount', 'The earth wire is disconnected'], 'C',
     'It trips on a live/neutral current imbalance, usually 30 mA', 'become unequal'),
    ('A.1', 'Where is the correct place for lightning protection of an antenna system?',
     ['Inside the shack next to the transceiver', 'Inside the transceiver', 'In the mains plug', 'Outdoors, not inside the house'], 'D',
     'Lightning protection belongs outdoors', 'correct place for lightning protection'),
    ('A.1', 'Ground rods for a tower should be at least:',
     ['300 mm long and 5 mm in diameter', '1500–2400 mm long and at least 12.5 mm in diameter',
      '10 m long and 50 mm in diameter', 'Any size, as long as they are copper'], 'B',
     '1500–2400 mm long, ≥ 12.5 mm diameter', '12.5 mm'),
    ('A.1', 'According to the RSGB pre-assessed configurations, a 40–160 m half-wave dipole fed with up to 400 W average power is likely to comply with ICNIRP if it is mounted at least ______ above most kinds of ground and nobody can remain closer than 2.2 m:',
     ['6.4 m', '1 m', '2.4 m', '25 m'], 'A',
     '6.4 m height and 2.2 m separation at 400 W', '6.4 m above'),
    # A.2 Interference and Immunity
    ('A.2', 'An unwanted emission at a whole-number multiple of the operating frequency is called:',
     ['A parasitic oscillation', 'A harmonic', 'Cross-modulation', 'An image'], 'B',
     'Harmonics are integer multiples of the wanted frequency', 'harmonic'),
    ('A.2', 'Interference picked up by a neighbour\'s equipment via its loudspeaker or mains cables is best tackled by:',
     ['Increasing your transmitter power', 'Moving to a higher band only', 'Using an SWR meter',
      'Common-mode chokes (ferrites) or filters on the affected cables at the victim equipment'], 'D',
     'Common-mode currents on the cables are choked at the victim equipment', 'common mode'),
    ('A.2', 'Radio equipment sold in the EU must meet the Radio Equipment Directive, which is:',
     ['ICNIRP 2020', 'Directive 2014/30/EU', 'Directive 2014/53/EU', 'T/R 61-02'], 'C',
     'RED = 2014/53/EU (the EMC Directive is 2014/30/EU)', ('2014/53/EU', 282, 333)),
    ('A.2', 'Overmodulation of an AM transmitter results in:',
     ['Splatter: distortion and a wider bandwidth that interferes with nearby frequencies', 'A cleaner signal',
      'Lower SWR', 'Reduced harmonics'], 'A',
     'Overmodulation produces splatter', 'overmodulation'),
    # A.3 Theory
    ('A.3', 'A fully charged 12 V, 100 Ah battery stores approximately:',
     ['12 Wh', '100 Wh', '1.2 kWh', '12 kWh'], 'C',
     '12 V × 100 Ah = 1200 Wh = 1.2 kWh', 'battery capacity'),
    ('A.3', 'The mains supply in Ireland is nominally:',
     ['110 V, 60 Hz', '230 V, 50 Hz', '400 V, 60 Hz', '230 V, 60 Hz'], 'B',
     '230 V, 50 Hz', 'frequency of 50 Hz'),
    ('A.3', 'The ITU frequency band from 30 MHz to 300 MHz is called:',
     ['HF', 'UHF', 'MF', 'VHF'], 'D',
     'VHF = 30–300 MHz', 'Table 7-A'),
    ('A.3', 'An absolute power of 32 dBW is approximately:',
     ['320 W', '1000 W', '1.6 kW', '3.2 kW'], 'C',
     '30 dBW = 1 kW, +2 dB ≈ ×1.6 → about 1.6 kW', '32 dBW'),
    # A.4 Components
    ('A.4', 'In the circuit shown, what does the (ideal) voltmeter V read?',
     ['4 V', '6 V', '8 V', '12 V'], 'C',
     'I = 12/3000 = 4 mA; V = 4 mA × 2 kΩ = 8 V', 'voltage divider', 'set11_q14'),
    ('A.4', 'Silvered mica capacitors are valued in RF circuits mainly for their:',
     ['Very large capacitance', 'Stability and low loss', 'Ability to handle mains voltage', 'Low cost'], 'B',
     'Silvered mica is stable and low-loss', 'silvered mica'),
    ('A.4', 'An electrolytic capacitor must be connected:',
     ['With the correct polarity', 'Only in AC circuits', 'Only in RF circuits', 'In series with an inductor'], 'A',
     'Electrolytics are polarised', 'electrolytic'),
    # A.5 TX/RX
    ('A.5', 'The driver stage of a transmitter:',
     ['Generates the carrier frequency', 'Filters out harmonics', 'Measures the output power',
      'Amplifies the signal to the level needed to drive the power amplifier'], 'D',
     'The driver raises the level for the PA', 'driver'),
    ('A.5', 'In a superheterodyne receiver, the difference between the local oscillator frequency and the signal frequency is the:',
     ['Intermediate frequency (IF)', 'Image frequency', 'Audio frequency', 'Beat frequency of the BFO'], 'A',
     'The mixer difference output is the IF', 'superheterodyne'),
    ('A.5', 'Compared with AM, an SSB voice transmission:',
     ['Uses twice the bandwidth', 'Transmits a full carrier', 'Uses about half the bandwidth and no carrier power', 'Cannot be used on HF'], 'C',
     'SSB: one sideband, carrier suppressed', 'suppressed carrier'),
    ('A.5', 'A dummy load is used to:',
     ['Increase antenna gain', 'Test or adjust a transmitter without radiating a signal', 'Measure field strength', 'Store energy'], 'B',
     'It absorbs the power instead of radiating it', 'dummy load'),
    # A.6 Antennas
    ('A.6', 'In the ground plane antenna shown, the elements marked "X" are the:',
     ['Directors', 'Radials, forming an artificial ground (counterpoise)', 'Traps', 'Reflectors'], 'B',
     'Elevated radials act as a counterpoise', 'radials', 'set11_q21'),
    ('A.6', 'Which type of feeder normally has the lowest loss?',
     ['Thin coaxial cable', 'Twisted mains flex', 'Waveguide at HF', 'Open-wire (ladder) line'], 'D',
     'Open-wire line has very low loss', 'open-wire'),
    ('A.6', 'A trap in a trap dipole is:',
     ['A parallel LC circuit that isolates the outer part of the antenna on the higher band', 'A resistor that absorbs power',
      'A lightning arrestor', 'A coaxial balun'], 'A',
     'Parallel-resonant traps "cut off" the outer sections on the higher band', 'trap dipole'),
    ('A.6', 'To obtain an ERP of 400 W from a 100 W transmitter, the net gain of feeder plus antenna must be:',
     ['3 dB', '12 dB', '6 dB', '20 dB'], 'C',
     '×4 = 6 dB', 'Effective Radiated Power'),
    # A.7 Propagation
    ('A.7', 'Which ionospheric layer remains at night and supports long-distance HF contacts?',
     ['D layer', 'F (F2) layer', 'E layer', 'Troposphere'], 'B',
     'The F2 layer persists at night', 'F2 layer'),
    ('A.7', 'A roughly 27-day variation in HF conditions is linked to:',
     ['The Moon\'s phases', 'Seasonal weather', 'The 11-year solar cycle', 'The rotation of the Sun'], 'D',
     'The Sun rotates about every 27 days', '27 days'),
    ('A.7', 'Short-lived summer openings on 6 m across Europe are usually due to:',
     ['Sporadic E', 'Ground wave', 'EME', 'D-layer absorption'], 'A',
     'Sporadic E is typical in summer on 10, 6 and 4 m', 'sporadic E'),
    ('A.7', 'Compared with the optical horizon, the radio horizon at VHF is:',
     ['Much closer', 'Exactly the same', 'Somewhat further away, because of atmospheric refraction', 'Unlimited'], 'C',
     'Refraction bends VHF waves slightly beyond the optical horizon', 'radio horizon'),
    # A.8 Measurements
    ('A.8', 'The oscilloscope is set to 1 V/div vertical and 0.5 ms/div horizontal. What is the frequency of the square wave?',
     ['250 Hz', '500 Hz', '2 kHz', '4 kHz'], 'B',
     'One cycle = 4 div × 0.5 ms = 2 ms → 500 Hz', 'oscilloscope', 'set11_q29'),
    ('A.8', 'To measure the voltage of a battery with a multimeter, you should:',
     ['Select a current range and connect it in series', 'Select the resistance range',
      'Select an AC range and connect it in series', 'Select a suitable DC voltage range and connect it across the terminals'], 'D',
     'Voltmeter: in parallel, on a DC range above the expected value', 'multimeter'),
    # B.1
    ('B.1', 'In the phonetic alphabet, "Uniform" represents the letter:',
     ['Y', 'V', 'U', 'W'], 'C', 'Uniform = U', 'Uniform'),
    # B.2
    ('B.2', '"QRM?" (as a question) means:',
     ['Are you ready?', 'Are you being interfered with?', 'What is my frequency?', 'Shall I send faster?'], 'B',
     'QRM? = are you being interfered with?', 'Are you being interfered with'),
    ('B.2', 'A station says "QSL via buro". This means:',
     ['Change frequency', 'Please wait', 'Send your QTH', 'I will confirm our contact by sending a card via the bureau'], 'D',
     'QSL card via the bureau', 'via buro'),
    ('B.2', 'In telegraphy, how do you turn a Q-code into a question?',
     ['Add a question mark after it', 'Send it twice', 'Send it in reverse', 'Add K before it'], 'A',
     'Simply add "?"', 'add a question mark'),
    # B.3
    ('B.3', 'Which is the correct voice distress call?',
     ['SOS SOS SOS', 'CQ emergency', 'MAYDAY MAYDAY MAYDAY', 'QRT QRT QRT'], 'C',
     'MAYDAY is the radiotelephony distress signal', 'MAYDAY'),
    ('B.3', 'The IARU Region 1 80 m emergency centre of activity is 3.760 MHz. Which frequency is used in Ireland?',
     ['3.700 MHz', '3.660 MHz', '3.630 MHz', '3.760 MHz'], 'B',
     'Ireland uses 3.660 MHz', 'Yes Yes 3.660'),
    ('B.3', 'Emergency traffic may be found within about ______ of an emergency centre of activity.',
     ['±1 kHz', '±500 kHz', '±5 MHz', '±20 kHz'], 'D',
     'Centres of activity: about ±20 kHz', '20 kHz from these centres'),
    # B.4
    ('B.4', 'In the normal ITU format, the third section of a call sign (the suffix):',
     ['Has not more than four characters, the last of which must be a letter', 'Must be exactly three digits',
      'Must start with a number', 'May have any number of characters'], 'A',
     'Up to four characters, ending in a letter', 'not more than four characters'),
    ('B.4', 'An Irish licensee, EI5ABC, operating in Denmark under CEPT arrangements, signs:',
     ['EI5ABC/DK', 'OZ/EI5ABC', 'DK/EI5ABC', 'EI5ABC/OZ'], 'B',
     'Visited country prefix + "/" + own call', 'OZ/EI5ABC'),
    ('B.4', 'The national prefix for Czechia is:',
     ['CZ', 'CS', 'CK', 'OK'], 'D', 'Czechia = OK', 'Czechia'),
    # B.5
    ('B.5', 'Which of these bands has NO emergency centre of activity used in Ireland?',
     ['12 m', '20 m', '17 m', '40 m'], 'A',
     'Bands with emergency CoAs: 80, 40, 20, 17, 15, 4, 2 m and 70 cm', 'Emergency centres of activity used in Ireland'),
    ('B.5', 'The 17 m band (18.068–18.168 MHz) is allocated in Ireland on a:',
     ['Secondary basis, 15 W EIRP', 'Secondary basis, 100 W', 'Primary basis, 400 W', 'Primary basis, 50 W'], 'C',
     '17 m: primary, 400 W, no contests', '18.068–18.168'),
    ('B.5', 'The propagation beacon range 24.929–24.931 MHz is in the:',
     ['10 m band', '12 m band', '15 m band', '17 m band'], 'B',
     '12 m = 24.890–24.990 MHz', '24.929–24.931'),
    ('B.5', 'In the IARU R1 80 m band plan, 3555 kHz is:',
     ['The SSB QRP centre of activity', 'The emergency centre of activity', 'A beacon frequency', 'The CW QRS (slow Morse) centre of activity'], 'D',
     '3555 kHz = CW QRS centre of activity', '3555 kHz'),
    # B.6
    ('B.6', 'The code-of-conduct principle of "comprehension" means:',
     ['Others may not share your knowledge; if you correct them, do it positively and politely', 'You must understand every language',
      'You must comprehend the licence conditions', 'Only experts may transmit'], 'A',
     'Offer helpful, constructive criticism politely', 'comprehension'),
    ('B.6', 'ComReg recognises self-regulation in amateur radio by:',
     ['Running the IRTS', 'Assigning frequencies for each QSO',
      'Recommending compliance with the IARU Region 1 band plans instead of setting its own mode segments', 'Monitoring all contacts'], 'C',
     'ComReg 09/45 recommends the IARU R1 band plans', 'self-regulation'),
    ('B.6', 'Between radio amateurs, surnames are:',
     ['Always required', 'Used rarely — first names (or nicknames) and call signs are normal', 'Used instead of call signs', 'Forbidden by law'], 'B',
     'First name + call sign is the norm', 'Surnames are used rarely'),
    # B.7
    ('B.7', 'The S value in a signal report should normally be taken from:',
     ['The transmitter power', 'Your own estimate of the distance', 'The SWR meter', 'Your receiver\'s S meter'], 'D',
     'Report the S-meter reading', 'S METER'),
    ('B.7', 'When answering a CQ, why is it usually not necessary to repeat your own call sign many times?',
     ['The CQ station will repeat back what they heard, giving you a chance to correct it', 'Call signs are optional',
      'ComReg forbids it', 'It wastes battery power'], 'A',
     'The calling station repeats back your call', 'repeat back'),
    ('B.7', 'Why should you ask "Is this frequency in use?" even when the frequency sounds clear?',
     ['It is required for every over', 'To test your microphone',
      'A station you cannot hear may be using it, and its partner may hear you', 'To measure the SWR'], 'C',
     'There may be no propagation path from the transmitting station to you', 'propagation path'),
    ('B.7', 'Some countries suggest that stations identify at least every:',
     ['30 seconds', '5 minutes', '2 hours', '24 hours'], 'B',
     'A 5-minute rule is suggested in some countries', '5 minutes'),
    ('B.7', 'Conducting business on the air in Ireland is:',
     ['Allowed at weekends', 'Allowed on VHF', 'Allowed if the business is radio-related',
      'Not allowed — amateur radio is of a non-pecuniary character'], 'D',
     'Non-pecuniary character', 'non-pecuniary'),
    # B.8
    ('B.8', 'The amateur service is carried out by duly authorised persons interested in radio technique solely with a personal aim and:',
     ['Without pecuniary interest', 'For commercial gain', 'On behalf of broadcasters', 'Only for emergency services'], 'A',
     'ITU definition: without pecuniary interest', 'pecuniary interest'),
    ('B.8', 'In the emission designator J3E, the letter E indicates:',
     ['Digital data', 'Morse by ear', 'Telephony (voice)', 'Facsimile'], 'C',
     'E = telephony', 'Telephony'),
    # B.9
    ('B.9', 'Under CEPT T/R 61-01, the duration of a "short visit" is:',
     ['Always exactly 30 days', 'Always one year', 'Unlimited', 'Defined by each country, usually up to 3 months'], 'D',
     'Set by each country, usually up to 3 months', 'usually up to 3 months'),
    ('B.9', 'The USA has adopted:',
     ['Both T/R 61-01 and T/R 61-02', 'Only T/R 61-01 (so Irish CEPT licensees can operate there as visitors)',
      'Only T/R 61-02', 'Neither'], 'B',
     'The USA adopted only T/R 61-01', 'only adopted'),
    ('B.9', 'The national prefix for Switzerland is:',
     ['HB9', 'SZ', 'CH', 'SW'], 'A', 'Switzerland = HB9', 'Switzerland'),
    # B.10
    ('B.10', 'If the address of your amateur station changes:',
     ['Nothing needs to be done', 'You must re-sit the HAREC exam', 'An amendment to the licence is required', 'You get a new call sign'], 'C',
     'The licence details must be updated (amendment)', 'amendment'),
    ('B.10', 'The land mobile power limit in the contiguous part of the 60 m band is:',
     ['50 W', '15 W EIRP (12 dBW)', '10 W', '200 W PEP'], 'B',
     'The 15 W EIRP limit also applies to /M', '15 W (12 dBW)'),
    ('B.10', 'In the station logbook, the power level is recorded in:',
     ['dBW or W', 'Amperes', 'Volts', 'S units'], 'A',
     'Power level (dBW or W)', 'power level (dBW or W)'),
]
