QUESTIONS = [
    # A.1 Safety
    ('A.1', 'The location and purpose of the station\'s main (master) power switch should be:',
     ['Known only to the licensee', 'Known to all family or club members', 'Hidden to prevent misuse', 'Marked only in the logbook'], 'B',
     'Everyone should know where it is', 'known to all family'),
    ('A.1', 'In Ireland, anyone carrying out electrical work in a domestic setting must by law be:',
     ['A licensed radio amateur', 'A member of the IRTS', 'Approved by ComReg', 'Registered with Safe Electric'], 'D',
     'Electrical contractors must register with Safe Electric', 'register with Safe Electric'),
    ('A.1', 'When operating a mobile station while driving, major adjustments such as band changes should be made:',
     ['When stationary', 'At high speed on motorways only', 'While overtaking', 'Never — mobile operation is illegal'], 'A',
     'Use hands-free operation; adjust when stationary', 'when stationary'),
    ('A.1', 'Why must you be careful where you locate a high-quality magnetic loop antenna indoors (e.g. in an attic)?',
     ['It attracts lightning', 'It is very heavy', 'It can cause intense heating of nearby conductors, creating a fire risk', 'It needs a ground rod'], 'C',
     'Strong near fields can heat nearby conductors', 'intense heating'),
    ('A.1', 'Most ICNIRP exposure limits are specified as values averaged over a period such as:',
     ['1 second', '6 or 30 minutes', '24 hours', '1 year'], 'B',
     'Time-averaged over e.g. 6 or 30 minutes', '6 or 30 minutes'),
    # A.2
    ('A.2', 'Splatter is:',
     ['A type of lightning damage', 'Fading on 10 m', 'Interference from solar panels',
      'Unwanted emissions outside the necessary bandwidth, typically from an overdriven or overmodulated transmitter'], 'D',
     'Splatter spreads energy onto adjacent frequencies', 'splatter'),
    ('A.2', 'Which of these is a common source of interference to amateur reception?',
     ['Poorly designed devices such as some solar PV installations and switch-mode power supplies', 'Lead-acid batteries',
      'Quartz crystals', 'Open-wire feeders'], 'A',
     'Poorly made digital devices and PV installations cause interference', ('solar PV', 282, 371)),
    ('A.2', 'Which of these is NOT a spurious emission?',
     ['A harmonic', 'A parasitic oscillation', 'The modulation within the necessary bandwidth', 'An intermodulation product radiated by the transmitter'], 'C',
     'The wanted modulation is not spurious', ('Spurious Emissions', 287, 291)),
    ('A.2', 'Cross-modulation in a receiver is usually caused by:',
     ['A low SWR', 'A very strong nearby signal overloading the receiver\'s front end', 'Using SSB', 'Using a crystal filter'], 'B',
     'Strong signals cause non-linear behaviour in the front end', ('cross-modulation', 205, 205)),
    # A.3
    ('A.3', 'Kirchhoff\'s voltage law states that, around a closed loop:',
     ['The sum of the voltage drops equals the source EMF', 'Current is the same in every branch',
      'Voltage equals current divided by resistance', 'Power is constant'], 'A',
     'KVL', ('Kirchhoff', 19, 22)),
    ('A.3', 'A sine wave has a peak value of 10 V. Its instantaneous value at 30° is:',
     ['10 V', '7.07 V', '5 V', '8.66 V'], 'C',
     '10 × sin 30° = 5 V', ('instantaneous', 38, 47)),
    ('A.3', 'The third harmonic of 7 MHz is:',
     ['10 MHz', '3.5 MHz', '14 MHz', '21 MHz'], 'D', '3 × 7 = 21 MHz', ('harmonics', 38, 50)),
    ('A.3', 'A Fast Fourier Transform (FFT) converts a digitised signal:',
     ['From DC to AC', 'From the time domain to the frequency domain', 'From analogue to digital', 'From FM to AM'], 'B',
     'FFT: time → frequency domain', 'Fast Fourier Transform'),
    # A.4
    ('A.4', 'The circuit shown is a:',
     ['Half-wave rectifier', 'Full-wave bridge rectifier', 'Band-pass filter', 'Voltage regulator using a transistor'], 'B',
     'Four diodes in a bridge give full-wave rectification', 'bridge rectifier', 'set13_q14'),
    ('A.4', 'The back-EMF induced in an inductor:',
     ['Opposes any change in the current through it', 'Adds to the applied voltage', 'Only exists in DC circuits', 'Is caused by the dielectric'], 'A',
     'Self-induction opposes changes of current', ('back-electromotive', 88, 93)),
    ('A.4', 'A Class A amplifier is:',
     ['The most efficient class', 'Used only for FM', 'Non-linear', 'The most linear but least efficient class'], 'D',
     'Class A conducts all the time: linear, inefficient', 'Class A'),
    # A.5
    ('A.5', 'The low-pass filter after a transmitter\'s power amplifier is there to:',
     ['Remove the audio', 'Increase the power', 'Attenuate harmonics', 'Reduce the SWR'], 'C',
     'Harmonics lie above the operating frequency', ('low-pass filter', 170, 187)),
    ('A.5', 'In a filter-type SSB transmitter, the sideband filter:',
     ['Generates the carrier', 'Removes the unwanted sideband', 'Multiplies the frequency', 'Measures modulation'], 'B',
     'Only one sideband is passed', ('SSB Transmitter', 177, 179)),
    ('A.5', 'The AGC in a receiver controls the gain of:',
     ['The RF and IF stages, according to signal strength', 'The transmitter', 'The BFO', 'The antenna'], 'A',
     'AGC reduces RF/IF gain on strong signals', ('Automatic Gain Control', 196, 197)),
    ('A.5', 'The squelch control of an FM receiver is normally set:',
     ['Fully off', 'To maximum', 'To the same level as the volume', 'Just above the point where background noise is muted'], 'D',
     'Set the threshold just above the noise', 'squelch'),
    # A.6
    ('A.6', 'The velocity factor of typical coax with a solid polyethylene dielectric is about:',
     ['0.1', '1.0', '0.66', '2.0'], 'C', 'About 0.66', ('velocity factor of', 207, 212)),
    ('A.6', 'Compared with a simple half-wave dipole, a folded dipole has:',
     ['A higher feed impedance (about 300 Ω)', 'A lower feed impedance (about 12 Ω)', 'A much higher gain', 'No resonance'], 'A',
     '≈ 4 × 73 Ω ≈ 300 Ω', 'Folded Dipole'),
    ('A.6', 'An end-fed half-wave antenna is normally fed through:',
     ['A 1:1 current balun only', 'A high-ratio impedance transformer (e.g. 49:1)', 'A dummy load', 'A low-pass filter only'], 'B',
     'The end impedance is several thousand ohms', 'End-Fed Half-Wave Antenna'),
    ('A.6', 'The horizontal pattern shown is typical of:',
     ['A half-wave dipole', 'A quarter-wave vertical', 'A multi-element Yagi pointing towards 0°', 'An isotropic radiator'], 'C',
     'Strong forward lobe, small back lobe', 'Yagi Radiation Pattern', 'set13_q24'),
    # A.7
    ('A.7', 'The lowest usable frequency (LUF) on an HF path rises when:',
     ['D-layer absorption increases (e.g. around midday)', 'Night falls', 'The MUF falls', 'You use higher power'], 'A',
     'More absorption raises the LUF', 'Lowest Usable Frequency'),
    ('A.7', 'Ground-wave propagation gives the greatest range on:',
     ['UHF', 'VHF', 'Microwaves', 'The lower frequencies, such as LF and MF (e.g. 160 m)'], 'D',
     'Ground-wave losses increase with frequency', ('ground wave', 262, 264)),
    ('A.7', 'Which is a VHF/UHF propagation mechanism?',
     ['D-layer absorption', 'Ground wave on 160 m', 'Tropospheric ducting', 'NVIS'], 'C', 'Ducting is a VHF/UHF mode', 'ducting'),
    ('A.7', 'Meteor scatter contacts typically consist of:',
     ['Long, steady QSOs', 'Short bursts lasting seconds', 'Contacts via the Moon', 'Ground-wave contacts'], 'B',
     'Ionised meteor trails last only briefly', 'meteor scatter'),
    # A.8
    ('A.8', 'Before measuring a resistor\'s value with an ohmmeter, you should:',
     ['Apply the supply voltage', 'Use the current range', 'Switch off the circuit and preferably disconnect one end of the resistor', 'Connect the meter in series'], 'C',
     'Ohmmeters are used on de-energised, isolated components', ('ohmmeter', 272, 281)),
    ('A.8', 'The oscilloscope trace shows the output of an AM transmitter. It shows:',
     ['Overmodulation', 'An unmodulated carrier', 'Correct modulation, less than 100%', 'Key clicks'], 'C',
     'The envelope varies smoothly without reaching zero', ('overmodulation', 272, 281), 'set13_q30'),
    # B
    ('B.1', 'The correct phonetic word for the letter H is:',
     ['Henry', 'Harry', 'Holland', 'Hotel'], 'D', 'H = Hotel', 'Hotel'),
    ('B.2', 'A station sends "QRX 3". This usually means:',
     ['Wait for three minutes', 'Send 3 dB more power', 'Readability 3', 'Change to channel 3'], 'B',
     'QRX + number = wait that many minutes', 'Wait for three minutes'),
    ('B.2', 'QUF (as a statement) means:',
     ['I have received the distress signal sent by…', 'I am closing down', 'Your signals are weak', 'I am ready'], 'A',
     'QUF concerns a distress signal', 'I have received the distress signal'),
    ('B.2', 'The abbreviation "PSE" means:',
     ['Power supply earth', 'Pause', 'Please', 'Pressure'], 'C', 'PSE = please', 'PSE Please'),
    ('B.3', 'The IARU emergency guidance suggests that emergency communications volunteers think of themselves as:',
     ['Commanders of the operation', 'Independent observers', 'Members of the press', 'Unpaid employees of the agency they serve'], 'D',
     'Unpaid employees, not in charge', 'unpaid employees'),
    ('B.3', 'Compared with contesting, emergency communications require:',
     ['Contacting as many random stations as possible', 'Teamwork and contacting specific stations quickly to pass messages',
      'Using maximum power at all times', 'Using only CW'], 'B', 'Teamwork, not competition', 'Teamwork is important'),
    ('B.3', 'Which two Irish emergency centres of activity differ from the IARU Region 1 band plan?',
     ['3.660 MHz and 7.115 MHz', '14.300 MHz and 18.160 MHz', '21.360 MHz and 144.800 MHz', '430.400 MHz and 433.775 MHz'], 'A',
     'The 80 m and 40 m Irish frequencies differ from IARU R1', 'Irish (different from IARU R1)'),
    ('B.4', 'If an Irish licence is surrendered or cancelled, the call sign:',
     ['Is given to the next applicant', 'Can be inherited', 'Is permanently revoked and will not be reissued', 'Is held for 5 years'], 'C',
     'Revoked call signs are not reissued', 'will not be reissued'),
    ('B.4', 'An Irish licensee visiting Scotland under CEPT should use the prefix:',
     ['GM/', 'MM/', 'SC/', '2M/'], 'B', 'Use the M-series prefix: MM/', 'in Scotland'),
    ('B.4', 'The national prefix for Latvia is:',
     ['LV', 'LA', 'LT', 'YL'], 'D', 'Latvia = YL', 'Latvia'),
    ('B.5', 'Which part of the 70 cm band is limited to 50 W (17 dBW)?',
     ['430.000–432.000 MHz', '432.000–440.000 MHz', '435.000–438.000 MHz', 'The whole band'], 'A',
     '430–432 MHz: 50 W; 432–440 MHz: 400 W', '430.000–432.000'),
    ('B.5', 'On 160 m in Ireland, the 10 W power limit applies to:',
     ['1.810–1.850 MHz', '1.800–1.810 MHz', '1.850–2.000 MHz', 'The whole band'], 'C',
     '400 W below 1.850 MHz, 10 W above', '1.850–2.000'),
    ('B.5', 'Which range of the 10 m band is reserved for propagation beacons?',
     ['28.000–28.070 MHz', '29.600–29.700 MHz', '28.500–28.600 MHz', '28.190–28.225 MHz'], 'D',
     '28.190–28.225 MHz', '28.190–28.225'),
    ('B.5', 'On which band are contests NOT permitted?',
     ['15 m', '12 m', '10 m', '80 m'], 'B', 'No contests on 60 m or the WARC bands', '24.890–24.990'),
    ('B.6', 'The principle of politeness reminds you that:',
     ['Only your QSO partner can hear you', 'Rude language is allowed on CW',
      'Many people may be listening, so remain in control of your language and tone', 'Politeness slows contacts down'], 'C',
     'Everyone can listen', 'Remain in control of your language'),
    ('B.6', 'In amateur jargon, "YL" and "OM" refer to:',
     ['A woman and a man', 'Yellow light and orange mode', 'Your location and other modes', 'Yesterday\'s log and old messages'], 'A',
     'YL = woman, OM = man', 'YL (woman)'),
    ('B.6', 'Not everything heard on the bands is good practice. You should:',
     ['Copy what most stations do', 'Avoid listening', 'Correct others on the air loudly', 'Be a good example and follow the recommended operating procedures'], 'D',
     'Be a good example on the air', 'be a good example'),
    ('B.7', 'A report of "59 plus 15" means:',
     ['Readability 5, strength 9, 15 W', 'Perfectly readable, S-meter 15 dB over S9', 'Strength 5, readability 9', '15 minutes late'], 'B',
     '15 dB over S9', 'dB over 9'),
    ('B.7', 'On phone, an over is usually ended by the word:',
     ['"Over"', '"Out"', '"Roger"', '"Break"'], 'A', 'Phone: "over"; Morse: K or KN', 'ends with the person saying over'),
    ('B.7', 'The first step before making a general call on a band is to:',
     ['Call CQ loudly', 'Set maximum power', 'Tune the ATU on a busy frequency',
      'Check which portion of the band to use by referring to the IARU R1 band plan'], 'D',
     'Always refer to the band plan', 'Always refer to the IARU R1 band plan'),
    ('B.7', 'When buying radio equipment, which marking indicates EU regulatory compliance?',
     ['UL', 'FCC', 'CE', 'IARU'], 'C', 'Look for the CE marking', 'CE type approval marks'),
    ('B.7', 'If a frequency in a band allocated on a secondary basis is not clear, you should:',
     ['Not use it', 'Use it at low power', 'Ask the primary user to move', 'Use it only on CW'], 'A',
     'Secondary users must not interfere', 'If a secondary allocation band frequency is not clear'),
    ('B.8', 'Which of these is in ITU Region 1?',
     ['Australia', 'Brazil', 'Japan', 'Africa'], 'D', 'Region 1: Europe, Africa, Middle East, former USSR, Mongolia', 'Mongolia'),
    ('B.8', 'An ITU emission designator has a minimum of:',
     ['One character', 'Three characters', 'Five characters', 'Seven characters'], 'B', 'e.g. J3E', 'minimum of three characters'),
    ('B.9', 'Can ComReg issue a HAREC certificate to a candidate living in Northern Ireland who passes the Irish exam?',
     ['No, only to residents of the Republic', 'Only with Ofcom approval',
      'Yes — it can then be used to obtain a UK licence from Ofcom', 'Only after 5 years'], 'C',
     'HAREC is issued no matter where the candidate lives', ('where they live', 326, 329)),
    ('B.9', 'The national prefix for Bulgaria is:',
     ['LZ', 'BG', 'BU', 'YU'], 'A', 'Bulgaria = LZ', 'Bulgaria'),
    ('B.9', 'The national prefix for (mainland) Portugal is:',
     ['PT', 'PO', 'CP', 'CT7'], 'D', 'Portugal = CT7 (in Table 21-A)', 'Portugal'),
    ('B.10', 'ComReg may suspend or revoke an Amateur Station Licence:',
     ['At any time without reason', 'Where there is serious or repeated non-compliance with the licence conditions',
      'If the licensee does not join the IRTS', 'If the licensee does not operate for a year'], 'B',
     'Serious or repeated non-compliance', 'suspend or revoke'),
    ('B.10', 'The rights under a club licence, including the call sign, belong to:',
     ['The nominated individual', 'ComReg', 'The IRTS', 'The club itself'], 'D', 'They vest in the club', 'vest in the club'),
    ('B.10', 'According to the ComReg guidelines, the /M suffix is spoken as:',
     ['"Slash mobile"', '"Portable"', '"Mike"', '"Moving"'], 'A',
     'ComReg says "slash mobile" (IARU recommends "stroke")', 'slash mobile'),
]
