QUESTIONS = [
    # A.1
    ('A.1', 'The fuse in a mains-powered piece of equipment should be fitted in the live lead:',
     ['On the mains side of the switch', 'In parallel with the switch', 'On the equipment side of the switch', 'Only in the neutral lead'], 'C',
     'Live lead, equipment side of the switch', 'equipment side of the switch'),
    ('A.1', 'When earthing several pieces of station equipment, you should:',
     ['Connect each device directly to a common earthing point rather than daisy-chaining them', 'Daisy-chain them from one to the next',
      'Earth only the transceiver', 'Use the mains neutral as earth'], 'A',
     'Avoid daisy-chaining earth connections', 'daisy-chaining'),
    ('A.1', 'Wide, flat earth straps are better than round wires for RF earthing because they:',
     ['Are cheaper', 'Are easier to solder', 'Look neater', 'Have lower inductance, and therefore lower impedance at RF'], 'D',
     'Wide straps have low inductance', 'low inductance'),
    ('A.1', 'Microphones and Morse keys in the shack should be:',
     ['Connected to the neutral', 'Either fully insulated or properly connected to an earthed chassis', 'Left floating', 'Connected to the antenna'], 'B',
     'Insulated or properly earthed', 'Microphones and Morse keys'),
    ('A.1', 'RF exposure calculators based only on far-field assumptions:',
     ['Are exact everywhere', 'Are required by ComReg', 'May be inaccurate or misleading for predicting exposure in the near field', 'Only work for VHF'], 'C',
     'Near fields are hard to predict', 'far field assumptions'),
    # A.2
    ('A.2', 'According to the Study Guide, the two routes by which EMC problems arrive are:',
     ['Radiated emissions and conducted emissions', 'AM and FM', 'Ionospheric and tropospheric paths', 'Primary and secondary allocations'], 'A',
     'Radio waves through the air, and RF currents conducted along wiring', 'radiated emissions and conducted emissions'),
    ('A.2', 'When a device malfunctions because it lacks immunity to legitimate amateur transmissions, this is known as:',
     ['Harmonic radiation', 'Splatter', 'Key clicks', 'Breakthrough'], 'D',
     'Lack of immunity to a legitimate signal = breakthrough', 'known as a BREAKTHROUGH'),
    ('A.2', 'An earthed screen (shield) around equipment or cables reduces interference by:',
     ['Increasing the signal voltage', 'Preventing external fields from reaching the circuits inside', 'Changing the frequency', 'Reducing the mains voltage'], 'B',
     'Shielding blocks radiated coupling', 'shielding'),
    ('A.2', 'Overdriving a linear amplifier to get "a bit more power" results in:',
     ['Cleaner signals', 'Lower harmonic content', 'Little extra power but much more distortion and splatter', 'Reduced power consumption'], 'C',
     'Drive levels must be kept within the linear range', ('linear amplifier', 282, 291)),
    # A.3
    ('A.3', 'A 7 Ah battery supplies a constant 0.5 A. Ignoring losses, how long until it is empty?',
     ['3.5 hours', '14 hours', '7 hours', '0.07 hours'], 'B', '7 Ah / 0.5 A = 14 h', 'battery capacity'),
    ('A.3', 'Two 1.5 V cells connected in series (positive to negative) give:',
     ['3 V', '1.5 V', '0.75 V', '0 V'], 'A', 'EMFs in series add', ('series', 16, 19)),
    ('A.3', 'A gain of about 9 dB corresponds to a power ratio of about:',
     ['3', '5', '2', '8'], 'D', '9 dB = 3 + 3 + 3 dB = ×8', ('decibel', 116, 119)),
    ('A.3', 'The period of a 7 MHz signal is approximately:',
     ['7 µs', '1.4 ms', '143 ns', '0.7 s'], 'C', 'T = 1/f = 1/7 000 000 s ≈ 143 ns', ('period', 38, 42)),
    # A.4
    ('A.4', 'A 10 Ω resistor and a 40 Ω resistor are connected in parallel. The total resistance is:',
     ['50 Ω', '25 Ω', '8 Ω', '4 Ω'], 'C', '(10 × 40)/(10 + 40) = 8 Ω', ('parallel', 28, 37)),
    ('A.4', 'In the transformer shown, what is the secondary voltage?',
     ['2.3 V', '23 V', '2300 V', '230 V'], 'B', 'Turns ratio 10:1 → 230/10 = 23 V', 'turns ratio', 'set14_q15'),
    ('A.4', 'In the circuit symbol of a PNP transistor, the arrow on the emitter:',
     ['Points inwards, towards the base', 'Points outwards, away from the base', 'Is on the collector', 'Is absent'], 'A',
     'NPN: arrow out; PNP: arrow in', 'PNP transistor'),
    # A.5
    ('A.5', 'The frequency stability of a VFO is improved by:',
     ['Using a high SWR', 'Overdriving the PA', 'Using a longer feeder',
      'Temperature-stable components, a buffer stage and a regulated supply'], 'D',
     'Methods of achieving frequency stability', ('frequency stability', 170, 187)),
    ('A.5', 'In an FM transmitter, the frequency deviation is proportional to:',
     ['The audio frequency', 'The amplitude (loudness) of the modulating audio', 'The supply voltage', 'The SWR'], 'B',
     'Louder audio = more deviation', ('deviation', 144, 160)),
    ('A.5', 'The sensitivity of a receiver is the:',
     ['Maximum signal it can handle', 'Width of its IF filter', 'Weakest signal that gives an acceptable signal-to-noise ratio', 'Accuracy of its dial'], 'C',
     'Ability to receive weak signals', ('sensitivity', 202, 205)),
    ('A.5', 'A double-conversion superheterodyne uses:',
     ['Two intermediate frequencies: a high first IF and a lower second IF', 'Two antennas', 'Two BFOs', 'Two power supplies'], 'A',
     'High first IF for image rejection, low second IF for selectivity', 'Double Conversion'),
    # A.6
    ('A.6', 'A waveguide is:',
     ['A balanced twin-lead', 'A coaxial cable with air dielectric', 'A type of antenna tuner', 'A hollow metal tube used as a feeder at microwave frequencies'], 'D',
     'Hollow conductive pipe for microwaves', ('Waveguide', 213, 214)),
    ('A.6', 'The figure shows a cross-section of coaxial cable. Its characteristic impedance depends on:',
     ['Its length', 'The ratio of D to d and the dielectric material', 'The thickness of the outer jacket', 'The power applied'], 'B',
     'Z₀ depends on the conductor diameters and the dielectric', ('Coaxial Line', 211, 212), 'set14_q22'),
    ('A.6', 'The voltage standing wave ratio (VSWR) is the ratio of:',
     ['Forward to reflected power', 'Antenna gain to feeder loss', 'Maximum to minimum voltage along the line', 'Input to output impedance'], 'C',
     'VSWR = Vmax / Vmin', ('standing wave ratio', 206, 223)),
    ('A.6', 'Which of these is an unbalanced antenna?',
     ['A quarter-wave vertical (ground plane)', 'A centre-fed half-wave dipole', 'A folded dipole', 'A doublet fed with ladder line'], 'A',
     'Verticals work against ground and suit unbalanced coax', ('unbalanced', 224, 253)),
    # A.7
    ('A.7', 'At night, the F1 and F2 layers:',
     ['Both disappear', 'Merge into a single F layer', 'Move below the D layer', 'Become the E layer'], 'B',
     'The F1/F2 split exists in daytime only', ('F1 layer', 259, 261)),
    ('A.7', 'A signal above the MUF for a path will:',
     ['Be absorbed by the D layer', 'Be reflected more strongly', 'Pass through the ionosphere and not return to earth on that path', 'Travel by ground wave'], 'C',
     'Above the MUF the wave is not returned', ('Maximum Usable Frequency', 269, 270)),
    ('A.7', 'In the figure, the region marked "X" is the:',
     ['Ground-wave zone', 'Skip (dead) zone', 'Reactive near field', 'Radio horizon'], 'B',
     'Beyond ground-wave range, closer than the sky-wave return', 'dead zone', 'set14_q27'),
    ('A.7', 'Around solar maximum, the number of sunspots:',
     ['Is zero', 'Has no relation to propagation', 'Falls to a minimum', 'Is high, and increased solar radiation raises ionisation and the MUF'], 'D',
     'More sunspots, more ionisation', 'sunspot'),
    # A.8
    ('A.8', 'Why should an ideal ammeter have a very low resistance?',
     ['So that it does not significantly affect the current being measured', 'So that it can measure voltage too',
      'To protect the battery', 'So that it can be connected in parallel'], 'A',
     'Any significant meter resistance changes the circuit', 'An ideal ammeter should have a low impedance'),
    ('A.8', 'A frequency counter is used to:',
     ['Count QSOs', 'Measure SWR', 'Measure the frequency of a signal accurately', 'Measure antenna gain'], 'C',
     'Licensees must have an accurate means of checking frequency', 'Frequency Counter'),
    # B
    ('B.1', 'The phonetic word for the letter Y is:',
     ['Yellow', 'Yankee', 'Yokohama', 'Yacht'], 'B', 'Y = Yankee', 'Yankee'),
    ('B.2', 'In Morse, which short form is often heard in place of "QRZ?"',
     ['K', 'AR', 'SK', 'A question mark "?" on its own'], 'D', '"?" alone asks who is calling', 'question mark ? on its own'),
    ('B.2', '"QRO?" (as a question) means:',
     ['Shall I increase power?', 'Shall I decrease power?', 'Are you ready?', 'Shall I stop?'], 'A', 'QRO? = shall I increase power?', 'Should I increase power'),
    ('B.2', 'Used on its own as an operational abbreviation, "R" means:',
     ['Repeat', 'Readability 5', 'Received; also a general "yes" or "confirmed"', 'Radio'], 'C',
     'R = received / confirmed', 'Received, also meaning'),
    ('B.3', 'During an emergency, a net control station gives you instructions. You should:',
     ['Ignore them unless you are licensed for emergencies', 'Follow those instructions', 'Change frequency', 'Ask for their licence'], 'B',
     'Follow net control instructions', 'net control station is giving you instructions'),
    ('B.3', 'The Fire Service is part of which Principal Response Agency?',
     ['An Garda Síochána', 'The Health Services Executive', 'The Irish Coast Guard', 'The Local Authorities'], 'D',
     'The Fire Service is a Local Authority service', 'Fire Service is a Local Authority service'),
    ('B.3', 'AREN (Amateur Radio Emergency Network) is run by:',
     ['The IRTS in co-operation with ComReg', 'An Garda Síochána', 'The HSE', 'The ITU'], 'A',
     'Run by the IRTS with ComReg', ('run by the', 314, 319)),
    ('B.4', 'Which is a valid normal Irish call sign?',
     ['EI6ABCDE', 'EI-ABC', 'EI6ABCD', '6EIABC'], 'C', 'EI + digit + 1–4 letter suffix', 'EI 6 A B C D'),
    ('B.4', 'The national prefix for Canada (used with a regional indicator) is:',
     ['VE', 'CA', 'CN', 'K'], 'A', 'Canada = VE (e.g. EI5ABC/VE3)', ('Canada', 323, 324)),
    ('B.4', 'An Irish licensee visiting Northern Ireland should use the prefix:',
     ['GI/', '2I/', 'NI/', 'MI/'], 'D', 'Use MI/, not GI/', 'MI / (not GI'),
    ('B.5', 'The maximum power for a fixed station on the 80 m band is:',
     ['10 W', '100 W', '400 W (26 dBW)', '1 kW'], 'C', '80 m: 400 W', '3.500–3.800'),
    ('B.5', 'On the 15 m band, maritime mobile operation is:',
     ['Not permitted', 'Permitted (at up to 10 W)', 'Permitted at 400 W', 'Permitted only in contests'], 'B',
     '15 m allows /MM', '21.000–21.450'),
    ('B.5', 'On the six 60 m spot frequencies listed in the ComReg guidelines, the power limit is:',
     ['200 W PEP', '15 W EIRP', '10 W PEP', '400 W PEP'], 'A', 'Spot frequencies: 200 W PEP', 'SPOT FREQUENCIES'),
    ('B.5', 'For SSB voice on the 40 m band you should use:',
     ['USB', 'AM', 'Either, by preference', 'LSB'], 'D', 'Below 10 MHz (except 60 m): LSB', 'you should use LSB'),
    ('B.6', 'According to the code of conduct, radio amateurs aim to be:',
     ['Colleagues and friends', 'Competitors at all times', 'Anonymous', 'Regulators of each other'], 'A',
     'Social feeling and friendly spirit', 'colleagues and friends'),
    ('B.6', 'Why can telegraphy (Morse) contacts succeed between operators who share no common language?',
     ['Morse is the same as English', 'Translators are provided', 'Because of the reliance on Q-codes and operational abbreviations', 'They cannot'], 'C',
     'Q-codes act as an international language', 'neither English nor the language'),
    ('B.6', 'The /QRP call sign suffix is:',
     ['Required in all countries', 'Not permitted in Ireland, and against regulations in some other countries such as Belgium', 'Required in Ireland below 5 W', 'Allowed only on 2 m'], 'B',
     'Not allowed in Ireland; illegal in e.g. Belgium', 'Belgium'),
    ('B.7', 'Readability R4 means:',
     ['Unreadable', 'Barely readable', 'Readable with considerable difficulty', 'Readable with practically no difficulty'], 'D',
     'R4', 'practically no'),
    ('B.7', 'The Morse transmission "OM2ABC OM2ABC DE EI5ABC KN" means:',
     ['EI5ABC is calling OM2ABC and wants only OM2ABC to reply', 'OM2ABC is calling EI5ABC',
      'EI5ABC is calling CQ', 'EI5ABC is closing down'], 'A', 'KN: only the called station', 'do not want any other stations'),
    ('B.7', 'When you select an LSB frequency, your transmitted signal occupies about:',
     ['2.7 kHz above the displayed frequency', '100 Hz around the displayed frequency', '2.7 kHz below the displayed frequency', '10 kHz either side'], 'C',
     'Stay inside the band plan allowing for the 2.7 kHz below the dial', '2.7 kHz bandwidth below'),
    ('B.7', 'IARUMS stands for:',
     ['International Amateur Radio Union Mobile Service', 'IARU Monitoring System', 'Irish Amateur Radio Union Membership Scheme', 'International Aeronautical Radio Unit'], 'B',
     'The IARU Monitoring System', 'IARU Monitoring System'),
    ('B.7', 'In Morse, the prosign <SK> indicates:',
     ['A request for a signal report', 'Please send slower', 'Sked', 'The end of a QSO'], 'D', '<SK> = end of QSO', 'end of a QSO'),
    ('B.8', 'The ITU Radio Regulations govern:',
     ['Only amateur radio', 'Only broadcasting', 'The legal and technical requirements of all users of radio frequencies', 'Only Region 1'], 'C',
     'All radio users', 'legal and technical requirements'),
    ('B.8', 'In an emission designator, the second symbol "1" means:',
     ['One channel containing digital information, with no subcarrier', 'One channel of analogue information', 'Two channels', 'Telephony'], 'A',
     'e.g. A1A, F1B', 'no subcarrier'),
    ('B.9', 'A condition of operating under a CEPT licence abroad is that you must:',
     ['Use your Irish power limits', 'Apply for a temporary licence', 'Use your Irish call sign without a prefix',
      'Learn about and strictly observe the regulations of the country you are visiting'], 'D',
     'Observe the visited country\'s rules', 'strictly observe'),
    ('B.9', 'The national prefix for Malta is:',
     ['MT', '9H', '9A', 'ML'], 'B', 'Malta = 9H', 'Malta'),
    ('B.9', 'The national prefix for Cyprus is:',
     ['CY', '5C', '5B', 'C4'], 'C', 'Cyprus = 5B', 'Cyprus'),
    ('B.10', 'An applicant who does not permanently reside in Ireland must submit:',
     ['Full particulars of the station, including contact details, station details and qualifications', 'Nothing extra',
      'A passport only', 'A letter from the IRTS'], 'A', 'Full particulars are required', 'does not permanently reside'),
    ('B.10', 'The geographic position of the station must be recorded in the logbook:',
     ['For all contacts', 'Only for maritime mobile operation', 'Only for land mobile operation', 'Never'], 'B',
     'Position logging is only required for /MM', 'With the exception of maritime mobile'),
    ('B.10', 'An amateur station on a ship must not be used to send messages that would otherwise be sent by:',
     ['Another amateur', 'The IRTS', 'The vessel\'s own wireless telegraphy station', 'Email'], 'C',
     'It must not replace the ship\'s station', 'vessel’s wireless telegraphy station'),
]
