QUESTIONS = [
    # A.1
    ('A.1', 'The protective EARTH conductor in a mains cable is coloured:',
     ['Blue', 'Brown', 'Green with a yellow stripe', 'Black'], 'C', 'Earth = green/yellow', 'green with a yellow'),
    ('A.1', 'Before working on a high-voltage power supply that has been switched off, you should:',
     ['Use a shorting stick to discharge the smoothing capacitors, even if bleeder resistors are fitted', 'Start work immediately', 'Touch the capacitors to test them', 'Rely on the bleeder resistors'], 'A',
     'Capacitors can hold charge for months; bleeders often fail', 'shorting stick'),
    ('A.1', 'According to the Study Guide, the correct place for lightning protection is:',
     ['Inside the shack, next to the radio', 'In the mains fuse box', 'Inside the transceiver', 'Outdoors, not inside the house'], 'D',
     'Lightning protection belongs outdoors', 'correct place for lightning protection'),
    ('A.1', 'When thunderstorms are forecast, you should:',
     ['Keep operating on low power', 'Disconnect and ground all feeders, preferably outside the building', 'Touch the feeder to discharge it', 'Raise the antenna'], 'B',
     'Disconnect and ground', 'When thunderstorms are forecast'),
    ('A.1', 'The primary adverse effect of RF EMF exposure is:',
     ['Hair loss', 'Magnetisation of the blood', 'Heating of human tissue', 'Radioactivity'], 'C',
     'Thermal effects', 'primary ADVERSE EFFECT'),
    # A.2
    ('A.2', 'Many EMC problems are reduced when power reduction cures them. What should you do next?',
     ['Resume full power immediately', 'Take further steps to identify the cause before resuming higher power', 'Remove your earth', 'Change band permanently'], 'B',
     'Find the cause first', 'identify the cause before resuming'),
    ('A.2', 'Magnetic loop antennas, despite their small size, can cause EMC issues because:',
     ['They radiate only harmonics', 'They need high SWR', 'They have surprisingly large near fields and invite close proximity', 'They are always unbalanced'], 'C',
     'Large near fields', 'Magnetic loop'),
    ('A.2', 'The "Donald Duck" effect on nearby FM channels is caused by:',
     ['Key clicks', 'Low power', 'A correct deviation setting', 'Splatter from an overdeviated or distorted FM transmission'], 'D',
     'FM splatter', 'Donald Duck'),
    ('A.2', 'An amplifier that oscillates at a frequency unrelated to its working frequency suffers from:',
     ['Parasitic oscillation', 'Harmonic distortion', 'Selective fading', 'Back-EMF'], 'A',
     'Internal feedback loop', 'PARASITIC OSCILLATIONS'),
    # A.3
    ('A.3', 'Conventional current flows:',
     ['From negative to positive', 'From positive to negative', 'Only in insulators', 'Only in AC circuits'], 'B',
     'Electron flow is opposite to conventional current', ('conventional current', 10, 19)),
    ('A.3', 'A 100 W lamp is used for 5 hours. The energy used is:',
     ['20 Wh', '500 kWh', '105 Wh', '0.5 kWh'], 'D', '100 × 5 = 500 Wh = 0.5 kWh', ('kilowatt-hour', 23, 27)),
    ('A.3', 'Increasing the power by 20 dB means multiplying it by:',
     ['20', '10', '100', '200'], 'C', '20 dB = ×100', ('decibel', 116, 119)),
    ('A.3', 'The phase difference between two signals is measured in:',
     ['Degrees (or radians)', 'Hertz', 'Volts', 'Seconds squared'], 'A', 'One cycle = 360°', ('phase', 38, 47)),
    # A.4
    ('A.4', 'Adding a second identical resistor in parallel with an existing one:',
     ['Doubles the total resistance', 'Halves the total resistance', 'Has no effect', 'Makes it zero'], 'B',
     'R/2 for two equal resistors in parallel', ('parallel', 28, 37)),
    ('A.4', 'The component marked "X" in the oscillator circuit shown is a:',
     ['Capacitor', 'Zener diode', 'Quartz crystal', 'Fuse'], 'C', 'Crystal symbol: a plate between two electrodes', 'Quartz Crystals', 'set19_q15'),
    ('A.4', 'Zener diodes are used to:',
     ['Amplify RF', 'Emit light', 'Rectify mains at high current', 'Set and stabilise the output voltage of power supplies'], 'D',
     'Voltage stabilisation', 'ZENER DIODES are used to set'),
    # A.5
    ('A.5', 'Over-deviation of an FM transmitter causes:',
     ['Lower bandwidth', 'Better audio quality', 'Reduced power', 'Excessive bandwidth and interference to adjacent channels'], 'D',
     'Too much deviation spreads the signal', ('deviation', 144, 160)),
    ('A.5', 'In a superhet receiver, the IF filter mainly determines the receiver\'s:',
     ['Sensitivity to image signals', 'Selectivity (adjacent-channel rejection)', 'Output power', 'Frequency stability'], 'B',
     'IF filters set selectivity', ('selectivity', 188, 205)),
    ('A.5', 'A squelch circuit:',
     ['Silences the audio output when no signal is present', 'Increases the volume', 'Removes static from SSB', 'Tunes the antenna'], 'A',
     'Squelch', ('Squelch', 198, 199)),
    ('A.5', 'Compared with a dedicated hardware filter, filtering in a DSP/SDR receiver is done:',
     ['By changing quartz crystals', 'With LC circuits only', 'Mathematically in software on the digitised signal', 'By the antenna'], 'C',
     'Digital filtering', ('DSP', 199, 202)),
    # A.6
    ('A.6', 'Ladder line (open-wire feeder) typically has, compared with coax:',
     ['Higher losses', 'Lower losses, but it must be kept away from metal objects', 'A characteristic impedance of 50 Ω', 'No velocity factor'], 'B',
     'Parallel lines have low loss', ('parallel lines', 209, 210)),
    ('A.6', 'The figure shows the voltage along a feeder. What is the SWR?',
     ['3:1', '1:1', '2:1', '4:1'], 'A', 'SWR = Vmax/Vmin = 3/1', ('standing wave ratio', 215, 223), 'set19_q22'),
    ('A.6', 'A folded dipole has a feed-point impedance of about:',
     ['50 Ω', '73 Ω', '600 Ω', '300 Ω'], 'D', 'About 4 × 73 ≈ 300 Ω', 'approximately 300 Ω'),
    ('A.6', 'Compared with a half-wave dipole, the gain of the dipole itself expressed in dBi is:',
     ['0 dBi', '2.15 dBi', '−2.15 dBi', '10 dBi'], 'B', '0 dBd = 2.15 dBi', '2.15 dBi'),
    # A.7
    ('A.7', 'The sunspot cycle lasts about:',
     ['1 year', '27 days', '11 years', '100 years'], 'C', 'About 11 years', '11 year'),
    ('A.7', 'Sporadic E, which allows VHF contacts up to about 2500 km, occurs mainly:',
     ['Only in winter nights', 'Only at solar minimum', 'From May to July, in the mornings and just before noon', 'Never in Europe'], 'C',
     'Irregular thick E-layer clouds', ('SPORADIC E', 260, 260)),
    ('A.7', 'The F2 layer:',
     ['Absorbs HF signals in daytime', 'Is the lowest layer', 'Exists only in winter', 'Is the highest layer and the main one for long-distance HF'], 'D',
     'F2 supports DX', ('F2 layer', 259, 261)),
    ('A.7', 'Signals in the VHF and UHF bands are usually limited to:',
     ['Worldwide coverage', 'Roughly line-of-sight distances, except during special propagation', 'Ground-wave ranges of thousands of km', 'Skip distances only'], 'B',
     'Line of sight', ('VHF', 266, 268)),
    # A.8
    ('A.8', 'In the figure, a voltmeter with an internal resistance of 1 MΩ is connected across the lower resistor. What does it read?',
     ['5 V', '10 V', '3.3 V', '0 V'], 'C', '1 MΩ ∥ 1 MΩ = 0.5 MΩ; 10 × 0.5/1.5 ≈ 3.3 V — the meter loads the circuit', 'not to affect the voltage', 'set19_q29'),
    ('A.8', 'A dummy load is used to:',
     ['Test a transmitter without radiating a signal', 'Increase the antenna gain', 'Measure frequency', 'Decode digital modes'], 'A',
     'Non-radiating load', 'Dummy Load'),
    # B
    ('B.1', 'The phonetic word for the letter Q is:',
     ['Queen', 'Quebec', 'Quality', 'Quiet'], 'B', 'Q = Quebec', ('Quebec', 334, 335)),
    ('B.2', '"QTH" means:',
     ['My time is…', 'My frequency is…', 'My location is…', 'My name is…'], 'C', 'QTH = location', 'My location is'),
    ('B.2', '"QRT" (as a statement) means:',
     ['Stop your transmission', 'Increase power', 'Send faster', 'Who is calling?'], 'A', 'QRT = stop transmitting', 'Stop your transmission'),
    ('B.2', '"QRP" (as a statement) means:',
     ['Increase your power', 'I am ready', 'Stop sending', 'Decrease your power'], 'D', 'QRP = decrease power (also low-power operation)', 'Decrease your power'),
    ('B.3', 'On phone, the international distress signal is:',
     ['SOS', 'PAN PAN', 'SECURITE', 'MAYDAY'], 'D', 'Voice = MAYDAY; Morse = SOS', 'MAYDAY'),
    ('B.3', 'In Morse telegraphy, the distress signal is:',
     ['MAYDAY', 'SOS, sent without the usual spaces between characters', 'CQD', 'QRRR'], 'B',
     '··· — — — ···', ('distress signal used in telegraphy', 349, 351)),
    ('B.3', 'In Ireland, the 2 m emergency centres of activity include:',
     ['144.300 MHz', '145.500 MHz', '144.525 MHz', '146.000 MHz'], 'C', '144.525 (SSB), 144.800, 144.850 MHz', '144.525'),
    ('B.4', 'The holder of EI5ABC operating from a car should sign:',
     ['EI5ABC/M', 'EI5ABC/P', 'EI5ABC/MOBILE', 'M/EI5ABC'], 'A', '/M = land mobile', 'land mobile'),
    ('B.4', 'The national prefix for Belgium is:',
     ['BE', 'BG', 'ON', 'BL'], 'C', 'Belgium = ON', 'Belgium'),
    ('B.4', 'A call sign beginning "GW" or "MW" indicates a licensee in:',
     ['Scotland', 'Northern Ireland', 'Guernsey', 'Wales'], 'D', 'W = Wales', 'Wales'),
    ('B.5', 'Is maritime mobile operation permitted on the 6 m band?',
     ['Yes, at 10 W', 'No', 'Yes, at 100 W', 'Only on CW'], 'B', 'No /MM on 6 m', '50.000–52.000'),
    ('B.5', 'Which band is NOT a secondary allocation in Ireland?',
     ['5 MHz (60 m)', '10 MHz (30 m)', '70 MHz (4 m)', '14 MHz (20 m)'], 'D', 'Secondary: 5, 10, 50, 70 MHz', '14.000–14.350'),
    ('B.5', 'The maximum land mobile power on the 2 m band is:',
     ['50 W', '10 W', '400 W', '25 W'], 'A', 'Land mobile limit 50 W', '144.000–146.000'),
    ('B.5', 'The emergency centre of activity used in Ireland on the 20 m band is:',
     ['14.100 MHz', '14.300 MHz', '14.230 MHz', '14.000 MHz'], 'B', '14.300 MHz', 'Yes Yes 14.300'),
    ('B.6', 'Radio amateurs say that they "work" each other. This means they:',
     ['Are employed by each other', 'Repair each other\'s equipment', 'Make contacts with one another', 'Compete in contests only'], 'C',
     'To work = to make contacts', 'To WORK means'),
    ('B.6', 'When offering criticism to another amateur, you should:',
     ['Aim to politely explain the issue, avoiding strong or impolite language', 'Criticise them publicly on the air', 'Ignore them entirely', 'Report them to the Gardaí'], 'A',
     'Helpful, constructive criticism', 'politely explain the issue'),
    ('B.6', 'Since "73" already stands for best regards, writing "best 73" or "73s" is:',
     ['Required', 'The IARU standard', 'Rude', 'Not necessary'], 'D',
     'Etiquette in written communication', 'not necessary to write best 73'),
    ('B.7', 'A Morse RST report of 599 means:',
     ['Weak signal, poor tone', 'Perfectly readable, extremely strong signal, perfect tone', 'Unreadable', 'Readable with difficulty'], 'B',
     'R5 S9 T9', ('599', 368, 370)),
    ('B.7', 'Before calling CQ on a frequency, you should:',
     ['Listen first and ask whether the frequency is in use', 'Transmit a long carrier', 'Call immediately', 'Change mode'], 'A',
     'Listen before transmitting', 'Is this frequency in use'),
    ('B.7', 'In Morse, the procedure signal sent before your call sign when answering a station is:',
     ['K', 'AR', 'DE', 'SK'], 'C', 'DE = from / this is', ('DE EI5ABC', 360, 371)),
    ('B.7', 'When choosing a frequency to call on, you should:',
     ['Pick one right next to a strong station', 'Use the lowest edge of the band', 'Transmit over a weak station', 'Avoid selecting frequencies too close to another nearby transmission'], 'D',
     'Operating procedure', 'Avoid selecting frequencies too close'),
    ('B.7', 'An "over" on phone is usually ended with:',
     ['"Over" or "K"', '"Roger"', '"Mayday"', '"73"'], 'A', 'Invitation to transmit', ('over', 360, 371)),
    ('B.8', 'Ireland is in ITU Region:',
     ['1', '2', '3', '4'], 'A', 'Region 1: Europe, Africa, Middle East, former USSR', ('Region 1', 314, 317)),
    ('B.8', 'In the designator F3E, the 3 indicates:',
     ['Data', 'No modulation', 'A single channel of analogue information', 'Two channels'], 'C', '3 = analogue', 'analogue'),
    ('B.9', 'Under T/R 61-01, how long may a visitor generally operate in a CEPT country without a local licence?',
     ['Unlimited', 'Up to three months (short visits)', 'One day', 'One year'], 'B', 'Temporary visits, not exceeding 3 months', 'usually up to 3 months'),
    ('B.9', 'T/R 61-02 deals with:',
     ['The HAREC exam certificate, allowing a local licence to be issued abroad', 'Temporary operation', 'Band plans', 'Beacons'], 'A',
     'Harmonised Amateur Radio Examination Certificate', 'T/R 61-02'),
    ('B.9', 'The national prefix for Portugal is:',
     ['PT', 'PO', 'P5', 'CT'], 'D', 'Portugal = CT', 'Portugal'),
    ('B.10', 'Your log must record, for each contact:',
     ['The other station\'s home address', 'Date, time (UTC), frequency/band, mode, call sign of the other station and power', 'The weather', 'The topic of conversation'], 'B',
     'Logbook contents', 'details to be included in the logbook'),
    ('B.10', 'When requested by ComReg, a licensee must:',
     ['Ignore the request', 'Pay a fine', 'Make the station and logbook available for inspection', 'Surrender the call sign'], 'C',
     'Inspection', 'made available for inspection'),
    ('B.10', 'Log times are recorded in UTC. Compared with Irish time, UTC is:',
     ['The same in winter and one hour behind in summer', 'Always one hour ahead', 'Always the same', 'Two hours behind in summer'], 'A',
     'UTC matches Irish winter time', 'one hour behind in the summer'),
]
