QUESTIONS = [
    # A.1
    ('A.1', 'The saying "it\'s the volts that jolt but the mills that kill" means:',
     ['Only high voltage is dangerous', 'It is the current (milliamps) through the body that kills', 'Mills (factories) are dangerous', 'Low voltages are always safe'], 'B',
     'It is the current that kills', 'the mills (milliamps) that kill'),
    ('A.1', 'In adverse circumstances, voltages as low as about ______ can kill.',
     ['3 V', '1 V', '30 V', '3000 V'], 'C', 'As low as 30 V with sufficient current', 'as low as 30 V'),
    ('A.1', 'The most dangerous path for an electric shock is:',
     ['From one hand, across the chest, to the other hand which is grounded', 'Through one finger only', 'From foot to foot', 'Through the hair'], 'A',
     'Hand-to-hand across the chest', 'worst scenario'),
    ('A.1', 'Why can you get an RF burn from an antenna even before touching it?',
     ['Antennas get hot from sunlight', 'Static from the feeder', 'Lightning', 'An electrical arc can form between the skin and a conductor at high RF voltage'], 'D',
     'High RF voltages can arc to the skin', 'electrical arc'),
    ('A.1', 'Which is particularly dangerous at microwave frequencies?',
     ['Using a dummy load', 'Looking into an active waveguide or standing close in front of an active microwave antenna', 'Touching a coax connector when switched off', 'Using a low-pass filter'], 'B',
     'Eyes can be damaged quickly by high RF power density', 'active waveguide'),
    # A.2
    ('A.2', 'Interference caused by unwanted, excessive spurious emissions from your station must be remedied:',
     ['At the victim\'s equipment only', 'By the neighbour', 'On the transmitting side', 'By ComReg'], 'C',
     'Excessive spurious emissions need remediation at the transmitter', 'remediation on the transmitting side'),
    ('A.2', 'The likelihood of causing interference is directly related to:',
     ['The strength of the field from your antenna (antenna type, power and distance)', 'The colour of the coax', 'The time of day only', 'The mode of the neighbour\'s TV'], 'A',
     'Field strength drives EMC problems', 'directly related to the strength'),
    ('A.2', 'A simple first step that reduces many EMC problems is:',
     ['Removing the station earth', 'Using a longer coax', 'Moving the antenna into the attic', 'Reducing the transmit power'], 'D',
     'Use no more power than necessary', 'reducing the transmit power'),
    ('A.2', 'An HF station should include a low-pass filter at the transmitter output with a cut-off at about:',
     ['3 MHz', '30 MHz', '300 MHz', '3 GHz'], 'B', 'Cut-off around 30 MHz', 'cut off at 30MHz'),
    # A.3
    ('A.3', 'A 50 W device runs for 20 hours. How much energy does it use?',
     ['1 kWh', '2.5 kWh', '70 Wh', '10 kWh'], 'A', '50 W × 20 h = 1000 Wh = 1 kWh', ('kilowatt-hour', 23, 27)),
    ('A.3', 'Which of these materials is a good electrical insulator?',
     ['Copper', 'Aluminium', 'Silicon', 'PTFE (a plastic)'], 'D', 'Plastics are insulators; silicon is a semiconductor', ('insulator', 10, 17)),
    ('A.3', 'An absolute power of 12 dBW is approximately:',
     ['12 W', '120 W', '16 W', '1.2 W'], 'C', '10 dBW = 10 W; +2 dB ≈ ×1.6 → about 16 W', ('12 dBW', 116, 119)),
    ('A.3', 'Electric field strength is measured in:',
     ['A/m', 'V/m', 'W', 'Ω'], 'B', 'E field in volts per metre', ('electric field strength', 70, 87)),
    # A.4
    ('A.4', 'What is the total capacitance between A and B?',
     ['200 pF', '100 pF', '50 pF', '10 000 pF'], 'C', 'Two equal capacitors in series: C/2 = 50 pF', ('series', 93, 101), 'set15_q14'),
    ('A.4', 'Replacing the air dielectric of a capacitor with a material of higher permittivity:',
     ['Increases the capacitance', 'Decreases the capacitance', 'Has no effect', 'Turns it into an inductor'], 'A',
     'Capacitance depends on the dielectric', ('dielectric', 93, 99)),
    ('A.4', 'An integrated circuit (IC) is:',
     ['A single large resistor', 'A type of valve', 'A coil wound on ferrite', 'Many components (transistors, resistors etc.) built on a single chip'], 'D',
     'Basic understanding of ICs', 'Integrated Circuits'),
    # A.5
    ('A.5', 'Which IF filter bandwidth is most suitable for receiving CW?',
     ['6 kHz', 'About 500 Hz', '15 kHz', '2.7 kHz'], 'B', 'CW is narrow; SSB ≈ 2.4–2.7 kHz; AM ≈ 6 kHz', 'Typical receiver IF filter bandwidths'),
    ('A.5', 'PEP stands for:',
     ['Primary Emission Power', 'Power Every Period', 'Peak Envelope Power', 'Pulse Energy Peak'], 'C',
     'Licence limits are PEP (except 60 m)', 'Peak Envelope Power'),
    ('A.5', 'A high-power linear amplifier in an amateur station:',
     ['Amplifies the transceiver output while keeping the waveform undistorted, within the licence power limit', 'Converts SSB into FM',
      'Removes the need for a low-pass filter', 'Allows any power level to be used legally'], 'A',
     'Linear amplifiers must preserve the waveform; power limits still apply', ('High Power Linear Amplifiers', 186, 187)),
    ('A.5', 'The figure shows a direct-sampling SDR receiver. What is block "X"?',
     ['DAC', 'BFO', 'ADC (analogue-to-digital converter)', 'NCO'], 'C',
     'The RF is digitised by an ADC before the DSP', 'Modern Receivers and SDR', 'set15_q20'),
    # A.6
    ('A.6', 'Why must water be kept out of coaxial cable?',
     ['It increases the velocity factor to 1', 'It turns coax into a waveguide', 'It cools the cable too much',
      'The braid wicks moisture, which changes the impedance and causes standing waves'], 'D',
     'Moisture ruins coax', ('wicks moisture', 282, 291)),
    ('A.6', 'A choke made by threading ferrite rings over a coaxial feeder (the "Maxwell" design) is used to:',
     ['Increase the SWR', 'Reduce common-mode currents on the outside of the coax', 'Convert 50 Ω to 200 Ω', 'Filter harmonics'], 'B',
     'A 1:1 current balun/choke', ('Maxwell design', 282, 291)),
    ('A.6', 'On the resonant half-wave dipole shown, at which point is the RF voltage highest?',
     ['P', 'R', 'Q', 'It is the same everywhere'], 'C',
     'Voltage is maximum at the ends, current at the centre', ('voltage', 229, 233), 'set15_q23'),
    ('A.6', 'Antenna gain differs from directivity because gain also takes into account:',
     ['The antenna\'s efficiency (losses)', 'The colour of the antenna', 'The transmitter power', 'The feeder length only'], 'A',
     'Gain = directivity × efficiency', 'Directivity, Efficiency, and Gain'),
    # A.7
    ('A.7', 'A large solar flare can cause:',
     ['Better conditions on 160 m', 'Tropospheric ducting', 'A sudden HF fade-out due to greatly increased D-layer absorption', 'Meteor showers'], 'C',
     'Flares increase ionisation in the D layer', ('flare', 255, 259)),
    ('A.7', 'The troposphere is the lowest part of the atmosphere, extending up to about:',
     ['1 km', '10–15 km', '100 km', '300 km'], 'B', 'Weather happens in the troposphere', ('troposphere', 259, 260)),
    ('A.7', 'The E layer:',
     ['Is highest at night', 'Exists only during solar minimum', 'Reflects only VHF', 'Is mainly a daytime layer at about 100–120 km that largely disappears at night'], 'D',
     'Daytime layer', ('E layer', 259, 261)),
    ('A.7', 'Which propagation mode uses the Moon as a passive reflector?',
     ['Earth–Moon–Earth (EME)', 'Sporadic E', 'Tropospheric ducting', 'Auroral scatter'], 'A',
     'EME (moonbounce)', ('Earth-Moon-Earth', 254, 271)),
    # A.8
    ('A.8', 'To measure current with a meter, the circuit must be:',
     ['Short-circuited', 'Opened (broken) so that the current passes through the meter', 'Switched off', 'Connected to an earth'], 'B',
     'Ammeter in series', 'circuit to remain open or broken'),
    ('A.8', 'A general-purpose multimeter used near a transmitting antenna:',
     ['Always reads correctly', 'Measures RF power', 'Becomes a frequency counter', 'May be affected by RF and give wrong readings'], 'D',
     'Unless designed for radio use, meters can be affected by RF', 'affected by RF near a transmitter'),
    # B
    ('B.1', 'According to the ICAO pronunciation, the number 4 is spoken:',
     ['FOW-er', 'FOUR', 'KAR-tay', 'FAW'], 'A', 'FOW-er', 'FOW-er'),
    ('B.2', 'On phone, saying "QSL?" with a questioning tone means:',
     ['Send me your QSL card', 'Change frequency?', 'Can you confirm reception of what we just exchanged?', 'What is your location?'], 'C',
     'A questioning tone turns a Q-code into a question', 'questioning tone of voice'),
    ('B.2', 'Someone says "Nothing seemed to happen on that QRG". Here, QRG means:',
     ['Location', 'Frequency', 'Power', 'Group'], 'B', 'QRG used as an abbreviation for frequency', 'Nothing seemed to happen on that QRG'),
    ('B.2', '"Being QRV" means:',
     ['Being interfered with', 'Being on low power', 'Leaving the station', 'Being ready / available'], 'D', 'QRV = ready', 'Being ready'),
    ('B.3', 'Distress signals must only be used when there is:',
     ['Grave and imminent danger to life', 'A power cut', 'Interference on your frequency', 'A contest'], 'A',
     'Distress = grave and imminent danger to life', 'grave and imminent danger'),
    ('B.3', 'If you receive emergency traffic you should:',
     ['Relay it to social media', 'Ask for a signal report', 'Listen carefully and write down all you can hear', 'Change frequency'], 'C',
     'Measures in case of emergency', 'write down all you can hear'),
    ('B.3', 'Without further training (e.g. from AREN), should you take on emergency communication roles beyond the basic measures?',
     ['Yes, any licensed amateur may', 'No', 'Yes, if you have a high-power station', 'Only on 2 m'], 'B',
     'Untrained operators must not impede emergency operations', 'should not assume any emergency communication roles'),
    ('B.4', 'A UK call sign beginning with "2E" belongs to a licensee in:',
     ['Estonia', 'Spain', 'Egypt', 'England'], 'D', '2E, G and M denote England', '2E or G'),
    ('B.4', 'The holder of EI0SWL visiting an Irish offshore island should sign:',
     ['EJ0SWL', 'EJ/EI0SWL', 'EI0SWL/EJ', 'EI0SWL/P'], 'A', 'Simply change EI to EJ', 'EJ0SWL'),
    ('B.4', 'The national prefix for Russia is:',
     ['RU', 'RS', 'UA', 'R1'], 'C', 'Russia = UA', 'Russia'),
    ('B.5', 'Which band is: primary, 400 W, contests permitted, maritime mobile permitted, with an Irish emergency centre of activity?',
     ['30 m', '40 m', '60 m', '12 m'], 'B', '40 m (7.115 MHz)', '7.000–7.200'),
    ('B.5', 'Is maritime mobile operation permitted on the 70 cm band?',
     ['No', 'Yes, at 10 W', 'Yes, at 50 W', 'Only above 432 MHz'], 'A', 'No /MM on 430 MHz', '432.000–440.000'),
    ('B.5', 'Which ComReg document describes all radio frequency allocations and uses in Ireland?',
     ['The IARU band plan', 'T/R 61-01', 'The Wireless Telegraphy Act', 'The Radio Frequency Plan for Ireland'], 'D',
     'Radio Frequency Plan for Ireland', 'Radio Frequency Plan for Ireland'),
    ('B.5', 'In the IARU R1 80 m band plan, 3735 kHz is the:',
     ['Emergency centre of activity', 'Digital voice centre of activity', 'Image centre of activity', 'CW QRP centre of activity'], 'C',
     '3735 kHz = image (SSTV etc.) centre of activity', '3735 kHz – Image'),
    ('B.6', '"Ham" is:',
     ['A colloquial term for a radio amateur', 'A type of antenna', 'A Q-code', 'An insult'], 'A', 'Colloquial term', 'colloquial term'),
    ('B.6', 'Sections B6 and B7 of the syllabus refer to which edition of the IARU Ethics and Operating Procedures guide?',
     ['1st', '2nd', '5th', '3rd'], 'D', 'The 3rd edition', '3rd edition'),
    ('B.6', 'Non-English-speaking operators sometimes use with each other:',
     ['Only Morse', 'Their national phonetic alphabet', 'CB jargon', 'No call signs'], 'B',
     'National phonetic alphabets are heard, e.g. in contests', 'national phonetic alphabet'),
    ('B.7', 'A commonly used S meter should read S9 on VHF/UHF with an input of about:',
     ['50 µV', '500 µV', '5 µV', '0.5 V'], 'C', '50 µV on HF, 5 µV on VHF/UHF', '5 µV on VHF'),
    ('B.7', 'In Morse, a CQ call aimed only at stations in Japan is sent as:',
     ['CQ JA CQ JA CQ JA DE EI5ABC EI5ABC EI5ABC K', 'CQ DX DE EI5ABC', 'JA DE EI5ABC KN', 'CQ JAPAN SK'], 'A',
     'JA is the national prefix for Japan', 'CQ JA CQ JA'),
    ('B.7', 'When working a rare DX station in a busy pile-up:',
     ['Long conversations are expected', 'Reports must be measured exactly', 'You should call continuously', 'Only the barest information is exchanged, often with a 59 / 599 report'], 'D',
     'Speed matters in pile-ups', 'barest of information'),
    ('B.7', 'Which mode, according to the Study Guide, always uses LSB?',
     ['FT8', 'RTTY', 'CW', 'FM'], 'B', 'RTTY uses LSB; FT8 typically USB', ('RTTY always', 338, 345)),
    ('B.7', 'IARUMS is interested in reports of:',
     ['Only intruders from outside Europe', 'Only contest cheating', 'All kinds of interference, including poorly designed devices', 'Only CB activity'], 'C',
     'All kinds of interference', 'interested in reports of all kinds'),
    ('B.8', 'In general, licensed amateur stations may only contact:',
     ['Other licensed amateur stations (with emergency exceptions)', 'Any station that answers', 'Ships and aircraft', 'Broadcast stations'], 'A',
     'Amateurs contact amateurs', 'permitted only to contact other licensed amateur stations'),
    ('B.8', 'In ITU emission designators, the third letter D means:',
     ['Telephony', 'Telegraphy by ear', 'Television', 'Data, e.g. computer files, telemetry or packet radio'], 'D', 'D = data', 'Data, e.g., computer'),
    ('B.9', 'Which non-European country has implemented T/R 61-01?',
     ['China', 'New Zealand', 'Brazil', 'India'], 'B', 'Also Australia, Canada, Israel, Peru, South Africa and the USA', 'New Zealand'),
    ('B.9', 'The national prefix for Denmark is:',
     ['DK', 'DN', 'OZ', 'DA'], 'C', 'Denmark = OZ', 'Denmark'),
    ('B.9', 'Can an Irish CEPT Class 1 licence holder get extra privileges in some countries beyond T/R 61-01?',
     ['A small number of countries may give additional privileges — you must research the country\'s regulations', 'No, never', 'Yes, in all CEPT countries', 'Only in the USA'], 'A',
     'Research the visited country\'s rules', 'additional operational privileges'),
    ('B.10', 'Besides complying with ComReg guidelines, the Wireless Telegraphy Regulations legally require you to:',
     ['Join a club', 'Operate weekly', 'Observe good engineering practices', 'Use only commercial equipment'], 'C',
     'Good engineering practice is a legal requirement', 'good engineering practices'),
    ('B.10', 'May an unlicensed person (e.g. a shortwave listener) operate your station?',
     ['No, never', 'Yes, but only under the direct supervision of the licensee', 'Yes, unsupervised', 'Only on 2 m'], 'B',
     'Direct supervision of the licensee', 'UNLICENSED PERSONS'),
    ('B.10', 'Which details of the station addresses are shown in an Irish licence?',
     ['None', 'Only the county', 'Only the Eircode', 'The addresses, including their GPS coordinates'], 'D',
     'Addresses with GPS coordinates', 'GPS coordinates'),
]
