QUESTIONS = [
    # A.1
    ('A.1', 'Why should you not fit a 13 A fuse in the plug of a device that draws only 1 A?',
     ['It would blow immediately', 'It is illegal in Ireland', 'It would not protect against faults drawing less than 13 A', 'It increases RF interference'], 'C',
     'Use the lowest suitable rating for the highest protection', 'lowest current rating suitable'),
    ('A.1', 'Why should a low-resistance DC path to ground (through an RF choke) be provided at the output of a valve linear amplifier?',
     ['To increase the output power', 'To stop a failed DC blocking capacitor putting high DC voltage on the antenna', 'To tune the antenna', 'To reduce harmonics'], 'B',
     'Protects against a shorted anode blocking capacitor', 'DC blocking capacitor'),
    ('A.1', 'Short-circuiting a high-capacity battery:',
     ['Is a good way to test it', 'Recharges it', 'Is harmless at 12 V', 'Risks fire or explosion'], 'D',
     'Never short-circuit a high-capacity battery', 'fire or explosion'),
    ('A.1', 'For mobile operation, the Study Guide recommends carrying:',
     ['A suitable fire extinguisher', 'A spare antenna only', 'A frequency counter', 'A dummy load'], 'A',
     'Mobile and battery safety', 'fire extinguisher'),
    ('A.1', 'If you set up a station at a public event (e.g. a field day), regarding RF exposure you have:',
     ['No responsibility', 'Responsibility only for licensed visitors', 'A duty of care towards the general public', 'Responsibility only if ComReg is present'], 'C',
     'Duty of care to the public', 'duty of care'),
    # A.2
    ('A.2', 'Older passive infrared (PIR) sensors in alarms or security lights may:',
     ['Improve your reception', 'Be falsely triggered by nearby transmissions because they lack immunity', 'Cause key clicks', 'Absorb harmonics'], 'B',
     'Older sensors may lack immunity', 'Passive Infrared'),
    ('A.2', 'Which antenna is generally less prone to causing EMC problems in the house?',
     ['An end-fed half-wave very close to the radio room', 'A magnetic loop on the desk', 'A Yagi pointed at the neighbour\'s house', 'A symmetrical half-wave dipole placed away from the house'], 'D',
     'Symmetrical designs, away from equipment, are less prone', 'less prone'),
    ('A.2', 'Bending parallel (open-wire) feeder sharply or running it near metal can cause:',
     ['Unequal currents and feedline radiation', 'Lower losses', 'Better matching', 'Higher velocity factor'], 'A',
     'The currents are no longer equal and opposite', 'feedline radiation'),
    ('A.2', 'Operating a transmitter or amplifier with its covers or shields removed is:',
     ['Recommended for cooling', 'Fine on HF', 'Unsafe and likely to cause EMC problems', 'Required for tuning'], 'C',
     'Never operate with covers removed', 'covers or shields removed'),
    # A.3
    ('A.3', 'A heater draws 2 A from 230 V. Its resistance is:',
     ['460 Ω', '232 Ω', '0.0087 Ω', '115 Ω'], 'D', 'R = V/I = 230/2 = 115 Ω', ('Ohm’s law', 20, 23)),
    ('A.3', 'Direct current (DC):',
     ['Flows in one direction only', 'Reverses direction 50 times a second', 'Exists only in antennas', 'Is the same as RF'], 'A',
     'DC vs AC', ('direct current', 10, 19)),
    ('A.3', 'A Software Defined Radio (SDR) used as a broadband receiver can:',
     ['Only receive one narrow channel', 'Only transmit', 'Digitise and display a wide range of frequencies at once', 'Work without an antenna'], 'C',
     'SDR as a broadband receiver', ('Software Defined Radio', 64, 69)),
    ('A.3', 'The wavelength of a 3.6 MHz signal is about:',
     ['8.3 m', '83 m', '36 m', '1080 m'], 'B', 'λ = 300/3.6 ≈ 83 m', ('wavelength', 38, 42)),
    # A.4
    ('A.4', 'The inductance of a coil is increased by:',
     ['Adding more turns or a ferrite/iron core', 'Using thicker insulation', 'Removing turns', 'Increasing the current'], 'A',
     'Turns and core material raise inductance', ('turns', 88, 93)),
    ('A.4', 'In a purely inductive AC circuit, the current:',
     ['Leads the voltage by 90°', 'Is in phase with the voltage', 'Lags the voltage by 90°', 'Is zero'], 'C',
     'Inductive: current lags', ('current lags', 88, 101)),
    ('A.4', 'In the bipolar transistor symbol shown, terminal 3 (with the arrow) is the:',
     ['Base', 'Collector', 'Gate', 'Emitter'], 'D',
     'The arrow marks the emitter; pointing out = NPN', 'Bipolar Junction Transistor', 'set16_q16'),
    # A.5
    ('A.5', 'The figure shows the spectrum of a voice transmission. Which mode is it?',
     ['LSB', 'AM', 'USB', 'FM'], 'C',
     'Energy only above the suppressed carrier = upper sideband', ('upper sideband', 140, 160), 'set16_q17'),
    ('A.5', 'In many SSB transmitters, the signal is generated at a fixed frequency and moved to the operating frequency by:',
     ['A frequency multiplier', 'A mixer fed by a VFO', 'The ALC', 'A low-pass filter'], 'B',
     'Mixing with a VFO translates the frequency', ('mixer', 177, 179)),
    ('A.5', 'The S meter reading in a receiver is typically derived from:',
     ['The signal level (e.g. via the AGC)', 'The transmitter power', 'The SWR', 'The audio volume control'], 'A',
     'S meter', ('S Meter', 197, 198)),
    ('A.5', 'In a fully digital SDR transmitter, the RF signal is generated directly by:',
     ['A crystal oscillator and frequency multiplier', 'A valve oscillator', 'A balanced modulator', 'Direct digital synthesis (an NCO and a DAC)'], 'D',
     'RF DDS', 'Fully Digital Transmitter'),
    # A.6
    ('A.6', 'For the feeder to run with low SWR, where should an ATU be placed?',
     ['At the transmitter', 'At the antenna feed point', 'Halfway along the feeder', 'In the mains supply'], 'B',
     'An ATU only matches what is on its transmitter side', 'Antenna Tuning Units'),
    ('A.6', 'The loss of a transmission line increases with:',
     ['Lower frequency and shorter length', 'Lower SWR', 'Higher frequency, greater length and higher SWR', 'Lower power'], 'C',
     'Line loss (attenuation)', 'Line Loss'),
    ('A.6', 'A Yagi radiates 100 W ERP forwards and 1 W ERP backwards. Its front-to-back ratio is:',
     ['20 dB', '10 dB', '100 dB', '3 dB'], 'A', '100:1 = 20 dB', ('Front-to-Back Ratio', 248, 249)),
    ('A.6', 'The gain of a parabolic dish antenna increases when:',
     ['The frequency is lowered', 'The dish is made smaller', 'The feeder is longer', 'The dish is made larger (or the frequency raised)'], 'D',
     'Gain depends on the dish size in wavelengths', 'Parabolic Antenna'),
    # A.7
    ('A.7', 'The critical frequency is measured by sending signals:',
     ['Horizontally along the ground', 'Vertically upwards (vertical incidence)', 'To the Moon', 'Through a waveguide'], 'B',
     'Highest frequency returned at vertical incidence', ('Critical Frequency', 269, 270)),
    ('A.7', 'Fading of HF signals can distort SSB or AM because:',
     ['The transmitter drifts', 'The SWR changes', 'Different frequencies within the signal can fade differently (selective fading)', 'The D layer reflects them'], 'C',
     'Multipath fading', ('Fading', 269, 269)),
    ('A.7', 'The D layer is found at a height of roughly:',
     ['60–90 km', '10 km', '300 km', '1000 km'], 'A', 'Lowest ionospheric layer', ('D layer', 259, 260)),
    ('A.7', 'For VHF line-of-sight paths, the radio horizon distance increases when:',
     ['The frequency is lowered to HF', 'AM is used', 'The weather is rainy', 'The antennas are raised higher'], 'D',
     'Higher antennas see further', ('radio horizon', 261, 262)),
    # A.8
    ('A.8', 'To measure the SWR on the feeder to the antenna, the SWR meter should be placed at:',
     ['P1', 'P2', 'Either P1 or P2 — the reading is the same', 'Inside the ATU'], 'B',
     'Measure on the feeder side of the ATU', 'SWR and Power', 'set16_q29'),
    ('A.8', 'Why can an ohmmeter damage some solid-state components?',
     ['It draws mains current', 'It measures in parallel', 'Its internal battery voltage may exceed the components\' limits', 'It produces RF'], 'C',
     'Ohmmeters apply their own voltage', 'internal batteries of an ohmmeter'),
    # B
    ('B.1', 'The ITU code word for the letter J is spelled:',
     ['Juliet', 'Juliett', 'Julia', 'Jupiter'], 'B', 'Juliett — with double T', 'Juliett'),
    ('B.2', 'In CW, "QRU?" is sometimes used as a polite way of suggesting that:',
     ['The contact could end soon', 'The other station should increase power', 'The frequency is busy', 'An emergency is in progress'], 'A',
     'Have you anything (more) for me?', 'polite way of implying'),
    ('B.2', '"QRS?" (as a question) means:',
     ['Shall I stop?', 'Shall I send faster?', 'Shall I increase power?', 'Shall I send more slowly?'], 'D', 'QRS? = decrease sending speed?', 'Should I decrease my sending speed'),
    ('B.2', 'The abbreviation "DX" means:',
     ['Direct transmission', 'Data exchange', 'Long distance, usually another continent', 'Distress'], 'C', 'DX = long distance', 'Long distance, usually'),
    ('B.3', 'Who decides whether the ITU emergency third-party provision applies to amateur stations in a country?',
     ['The IARU', 'The national administration', 'The ITU Secretary-General', 'The local club'], 'B',
     'National administrations determine applicability', 'National administrations determine'),
    ('B.3', 'Compared with a home installation, an emergency station should be:',
     ['Larger and fixed', 'Only for VHF', 'Used only at night', 'Portable and able to be set up and operated anywhere quickly'], 'D',
     'Day-to-day vs emergency communication', 'set up and operate anywhere'),
    ('B.3', 'In an emergency, your primary task is:',
     ['Communication — getting the message through by any suitable means', 'Showing off your equipment', 'Making as many QSOs as possible', 'Testing your antennas'], 'A',
     'Communication, by whatever means', 'primary task is communication'),
    ('B.4', 'Which is a valid normal Irish call sign with a one-letter suffix?',
     ['EI3', 'EI-F', 'EI3F', '3EIF'], 'C', 'EI + digit + 1–4 letters', 'EI 3 F EI 3 R D B'),
    ('B.4', 'Which of these complies with the normal ITU call sign rules?',
     ['26A', 'M6A', '2EABCD', 'EI4RGD7'], 'B', 'M (letter) – 6 – A', 'Examples of INCORRECT'),
    ('B.4', 'The national prefix for Sweden is:',
     ['SM', 'SW', 'SE', 'OH'], 'A', 'Sweden = SM', 'Sweden'),
    ('B.5', 'Which band is limited to 50 W (17 dBW) for a fixed station?',
     ['4 m', '6 m', '2 m', '10 m'], 'A', '4 m: 50 W; 6 m: 100 W', '69.900–70.500'),
    ('B.5', 'The emergency centre of activity used in Ireland on the 15 m band is:',
     ['21.150 MHz', '21.200 MHz', '21.450 MHz', '21.360 MHz'], 'D', '21.360 MHz (IARU R1)', '21.360'),
    ('B.5', 'Why does the IARU R1 band plan say that contests should not take place on the WARC bands?',
     ['They are reserved for beacons', 'Because of their small bandwidth', 'They are secondary everywhere', 'They have no propagation'], 'B',
     'WARC bands are narrow', 'small bandwidth'),
    ('B.5', 'You may transmit on the beacon-exclusive frequencies only if:',
     ['You use CW', 'It is night time', 'You are authorised by ComReg and part of a recognised beacon group', 'You use less than 5 W'], 'C',
     'Beacons need special authorisation', 'International Beacon Project'),
    ('B.6', 'Which language may be used on the amateur bands?',
     ['English only', 'Irish only', 'Esperanto only', 'Any language of choice — though English is most widely used'], 'D',
     'Anyone can converse in their language of choice', 'language of choice'),
    ('B.6', 'In Ireland, identifying your transmissions with anything other than your exact assigned call sign is:',
     ['Against the regulations (illegal)', 'Acceptable on VHF', 'Acceptable in contests', 'Encouraged for privacy'], 'A',
     'Use the exact call sign', 'exact call sign'),
    ('B.6', 'Does the amateur radio community have its own police to enforce the rules?',
     ['Yes, the IARU police', 'Yes, the IRTS', 'No — only the authorities can deal with breaches of the law', 'Yes, any licensee can act'], 'C',
     'Self-discipline, but only the authorities enforce', 'own police services'),
    ('B.7', 'If your receiver has no S meter, you should report signal strength:',
     ['As S9 always', 'Using the descriptions in the S table', 'As 0', 'In watts'], 'B',
     'Use the S table if there is no meter', 'no S -meter'),
    ('B.7', 'Which is an acceptable short Morse reply to a CQ, for example in a contest-style QSO?',
     ['CQ EI6XYZ', 'QRZ? QRZ?', 'SK EI6XYZ', 'EI6XYZ'], 'D', 'Just your call sign may suffice', ('EI6XYZ K N', 366, 366)),
    ('B.7', 'In Morse, EI5ABC calling W1ZZZ sends:',
     ['W1ZZZ DE EI5ABC', 'EI5ABC DE W1ZZZ', 'DE W1ZZZ EI5ABC', 'EI5ABC W1ZZZ K'], 'A',
     'The called station first', 'W1ZZZ DE EI5ABC'),
    ('B.7', 'A series of short overs in a QSO is usually considered:',
     ['Several separate contacts', 'Illegal', 'A single transmission', 'A contest exchange'], 'C', 'For identification purposes', 'SINGLE TRANSMISSION'),
    ('B.7', 'Adding "PSE" before K at the end of a Morse CQ call is:',
     ['Required by the IARU', 'Optional and courteous, but not recommended in the IARU and ITU guides', 'Illegal', 'A distress signal'], 'B',
     'PSE is optional', 'PSE may be courteous'),
    ('B.8', 'ITU Region 3 includes:',
     ['Europe', 'South America', 'Africa', 'Asia east of and including Iran, and most of Oceania'], 'D',
     'Region 3', 'east of and including Iran'),
    ('B.8', 'The first letter J in J3E means:',
     ['Amplitude modulation, single sideband, suppressed carrier', 'Frequency modulation', 'Phase modulation', 'Double sideband with carrier'], 'A',
     'J = SSB suppressed carrier', 'Amplitude modulation, single sideband'),
    ('B.9', 'Regarding T/R 61-01 and T/R 61-02:',
     ['Every country in the world has adopted both', 'No country outside Europe has adopted either',
      'Some countries have adopted only one of them, and a few neither', 'They are binding EU law'], 'C',
     'CEPT only makes recommendations', 'Some countries have only adopted one'),
    ('B.9', 'Canadian amateurs visiting the USA:',
     ['Use a W prefix', 'Continue to use the Canadian approach of adding a suffix', 'Need a US exam', 'Use the prefix VE/'], 'B',
     'A quirk noted in the Study Guide', 'Canadians visiting USA'),
    ('B.9', 'When visiting a country that uses regional indicators (e.g. England = M), you should:',
     ['Use them, even if not shown in T/R 61-01, unless the country makes them optional for visitors', 'Never use them',
      'Use only your Irish call sign', 'Use them only on VHF'], 'A', 'Use regional indicators', 'REGIONAL INDICATORS'),
    ('B.10', 'Requests for changes to Irish licence details should be made:',
     ['By post to the IRTS', 'By phone to the Gardaí', 'At the exam centre', 'Via the ComReg eLicensing website'], 'D',
     'eLicensing', 'made via the eLicensing website'),
    ('B.10', 'If an amateur station on a vessel interferes with the ship\'s own radio station, the amateur station must:',
     ['Reduce power to 1 W', 'Change band', 'Cease use until the cause has been remedied', 'Continue, as amateurs have priority'], 'C',
     'The ship\'s station takes priority', 'must cease'),
    ('B.10', 'The /P (portable) suffix:',
     ['Is required when away from home', 'Used to exist in Irish regulations but is no longer permitted', 'Is required by CEPT', 'Is permitted on VHF only'], 'B',
     'Irish regulations no longer allow /P', 'used to exist in the Irish regulations'),
]
