QUESTIONS = [
    # A.1
    ('A.1', 'In high-voltage power supplies, a bleeder resistor is connected across each smoothing capacitor to:',
     ['Increase the output voltage', 'Allow the capacitors to discharge after the power is switched off', 'Filter RF', 'Act as a fuse'], 'B',
     'Capacitors may hold charge for months or even years', 'bleeder resistor should be connected'),
    ('A.1', 'Microswitches in a valve power amplifier are fitted so that:',
     ['The fan starts', 'The band changes', 'The SWR is measured', 'The high-voltage supply is automatically disconnected when the cover is removed'], 'D',
     'Interlocks', 'Microswitches'),
    ('A.1', 'Soldering should be carried out:',
     ['In a closed cupboard', 'Only outdoors in rain', 'With the iron held near the face', 'In a well-ventilated area, avoiding inhaling the fumes'], 'D',
     'Chemicals and fumes', 'Soldering should be carried out'),
    ('A.1', 'In open-wire feeder, which type of static discharger should be used?',
     ['A gas-filled coax arrestor only', 'A ferrite choke', 'A spark-gap type', 'A fuse'], 'C',
     'Spark gaps for open-wire lines', 'spark gap type static dischargers'),
    ('A.1', 'Heating of body tissue by RF is a particular risk when:',
     ['The heat cannot be dissipated quickly enough by the body\'s natural cooling', 'The frequency is very low', 'The antenna is resonant', 'You wear glasses'], 'A',
     'Eyes are especially vulnerable', 'cannot be dissipated'),
    # A.2
    ('A.2', 'Electromagnetic compatibility (EMC) is:',
     ['A type of antenna', 'The avoidance of interference between any two pieces of electronic equipment', 'A licence condition only for repeaters', 'The SWR of a system'], 'B',
     'Definition', 'avoidance of interference between'),
    ('A.2', 'Conducted emissions are:',
     ['Radio waves travelling through the air', 'Signals from the ionosphere', 'Sound from a loudspeaker', 'RF currents conducted onto or from connected wiring, such as mains cables'], 'D',
     'As opposed to radiated emissions', 'CONDUCTED EMISSIONS are'),
    ('A.2', 'Almost all equipment sold in the EU carries the CE mark, which requires it to have:',
     ['A specific colour', 'Immunity from legitimate radio transmissions', 'An amateur licence', 'A 30 MHz low-pass filter'], 'B',
     'EU EMC directives', 'IMMUNITY from legitimate radio transmissions'),
    ('A.2', 'Harmonic distortion of a 40 m signal can cause significant interference on:',
     ['The 20 m band', 'The 80 m band', 'The 160 m band', 'Only 40 m'], 'A',
     'The 2nd harmonic of 7 MHz is 14 MHz', 'distortion of a signal on the 40 m band'),
    # A.3
    ('A.3', 'A 230 V supply delivers 0.5 A. The power is:',
     ['460 W', '230.5 W', '115 W', '0.002 W'], 'C', 'P = V × I = 230 × 0.5 = 115 W', ('Electric Power', 23, 25)),
    ('A.3', 'The SI unit of capacitance is the:',
     ['Henry', 'Farad', 'Siemens', 'Weber'], 'B', 'Capacitance in farads', ('farad', 11, 15)),
    ('A.3', 'An absolute level of 0 dBW equals:',
     ['0 W', '10 W', '1 mW', '1 W'], 'D', 'dBW is relative to 1 W', ('dBW', 116, 119)),
    ('A.3', 'A signal with a frequency of 145 MHz is in which range?',
     ['VHF (30–300 MHz)', 'HF (3–30 MHz)', 'UHF (300–3000 MHz)', 'MF (300–3000 kHz)'], 'A', '2 m band, VHF', '30–300 MHz'),
    # A.4
    ('A.4', 'What is the total inductance of the two coils shown (assuming no mutual coupling)?',
     ['40 µH', '20 µH', '10 µH', '5 µH'], 'C', 'Equal inductors in parallel: L/2 = 10 µH', ('Inductors in Series and Parallel', 90, 91), 'set20_q14'),
    ('A.4', 'A diode allows current to flow:',
     ['In both directions equally', 'In one direction only (when forward biased)', 'Only at RF', 'Only through its case'], 'B',
     'Rectifying behaviour', ('forward', 120, 121)),
    ('A.4', 'Light emitting diodes (LEDs) are used:',
     ['Only as rectifiers', 'As voltage references', 'As tuning capacitors', 'In household lighting and instrument displays'], 'D',
     'LED uses', 'LIGHT EMITTING DIODES'),
    # A.5
    ('A.5', 'A CW transmitter with a keying waveform that has too short a rise time will produce:',
     ['Key clicks', 'Chirp-free signals', 'Lower bandwidth', 'Better readability'], 'A',
     'Shape the keying waveform', ('rise time', 159, 163)),
    ('A.5', 'The ALC (automatic level control) in a transmitter:',
     ['Measures frequency', 'Reduces the drive to prevent the amplifier being overdriven', 'Sets the IF', 'Tunes the antenna'], 'B',
     'Prevents overdriving', ('ALC', 170, 187)),
    ('A.5', 'In the receiver shown, a CW signal at the IF of 455 kHz beats with the BFO. What audio tone is heard?',
     ['455 kHz', '911 kHz', '1 kHz', '456 Hz'], 'C', '456 − 455 = 1 kHz', ('BFO', 190, 197), 'set20_q19'),
    ('A.5', 'Automatic gain control (AGC) in a receiver:',
     ['Keeps the output level more constant as signal strength changes', 'Changes the frequency', 'Removes the BFO', 'Increases selectivity'], 'A',
     'AGC', ('Automatic Gain Control', 196, 197)),
    # A.6
    ('A.6', 'The velocity factor of a coaxial cable with solid polyethylene dielectric is about:',
     ['0.1', '1.5', '0.95', '0.66'], 'D', 'Waves travel slower in the dielectric', ('velocity factor of', 207, 212)),
    ('A.6', 'The feed-point impedance of a half-wave dipole is:',
     ['300 Ω', '30–80 Ω, depending on its height above the ground', '600 Ω', '1 Ω'], 'B', 'A 1:1 balun allows 50 Ω coax to be used', 'depending on its height above the ground'),
    ('A.6', 'A trap dipole works on several bands because:',
     ['Parallel resonant traps isolate the outer sections on the higher band', 'It has no feeder', 'It is non-resonant', 'It uses a waveguide'], 'A',
     'Traps act as switches', ('TRAP DIPOLE', 238, 238)),
    ('A.6', 'Compared with a single-element vertical, a Yagi antenna:',
     ['Is omnidirectional', 'Has no gain', 'Concentrates radiation in one direction, giving gain', 'Works only on HF'], 'C',
     'Directional beam', ('Yagi', 242, 246)),
    # A.7
    ('A.7', 'The Sun follows an activity cycle of approximately:',
     ['27 days', '11 years', '1 year', '22 months'], 'B', '11-year solar cycle', '11-year activity'),
    ('A.7', 'Which ray in the figure produces the longer skip distance?',
     ['Ray B (high angle)', 'Both are the same', 'Neither returns', 'Ray A (low angle)'], 'D',
     'Lower radiation angles reach further per hop', ('angle', 262, 266), 'set20_q26'),
    ('A.7', 'At night, the D layer:',
     ['Disappears, so absorption of lower HF signals falls', 'Becomes the strongest layer', 'Merges with F2', 'Blocks all HF signals'], 'A',
     'D layer needs sunlight', ('D layer', 259, 260)),
    ('A.7', 'The Lowest Usable Frequency (LUF) on a path is mainly limited by:',
     ['Ground conductivity', 'Feeder loss', 'D-layer absorption', 'Antenna height'], 'C', 'Absorption rises at lower frequencies', ('LUF', 269, 271)),
    # A.8
    ('A.8', 'To measure voltage, the meter is connected:',
     ['In series with the circuit', 'Across the points (in parallel) where voltage is to be measured', 'To the antenna', 'Between earth and neutral only'], 'B',
     'Voltmeter in parallel', 'MEASURE VOLTAGE'),
    ('A.8', 'A multimeter (multi-range meter) can measure:',
     ['Current, resistance and voltage', 'Only SWR', 'Only frequency', 'Only RF power'], 'A',
     'Multimeter', 'MULTI- RANGE METER'),
    # B
    ('B.1', 'In the ITU phonetic alphabet, the letter A is:',
     ['Apple', 'Able', 'Alfa', 'Alpha'], 'C', 'Spelled "Alfa"', ('Alfa', 334, 335)),
    ('B.2', '"QRL?" means:',
     ['Is the frequency in use?', 'What is your location?', 'Shall I stop?', 'Who is calling?'], 'A', 'QRL? = are you busy / is the frequency in use?', ('QRL', 346, 349)),
    ('B.2', '"QRU" (as a statement) means:',
     ['I am ready', 'I have nothing for you', 'Increase power', 'Fading'], 'B', 'QRU = I have nothing for you', 'I have nothing for you'),
    ('B.2', 'The first twelve Q-codes were standardised in:',
     ['1909', '1950', '2012', '1912'], 'D', 'Q-codes date from 1909; first twelve standardised in 1912', 'standardised in the 1912'),
    ('B.3', 'According to the ITU, amateur stations may transmit international communications on behalf of third parties:',
     ['At any time', 'Never', 'Only in case of emergencies or disaster relief', 'Only for businesses'], 'C',
     'Emergency exception', 'on behalf of third parties only in case'),
    ('B.3', 'The distress signal used on phone (voice) is:',
     ['SOS', 'MAYDAY', 'PAN', 'HELP'], 'B', 'MAYDAY by voice; SOS by Morse', ('Radiotelephony', 349, 351)),
    ('B.3', 'In Ireland, 3.660 MHz is listed as an emergency centre of activity on the:',
     ['80 m band', '40 m band', '160 m band', '60 m band'], 'A', '80 m', 'Yes Yes 3.660'),
    ('B.4', 'An Irish licensee visiting Scotland should use the prefix:',
     ['GS/', 'MS/', 'SC/', 'MM/'], 'D', 'MM/ in Scotland', 'MM/ in Scotland'),
    ('B.4', 'Call sign prefixes identify:',
     ['Only the operator\'s age', 'Only the band', 'The country, and sometimes the region and licence class', 'The mode in use'], 'C',
     'Prefixes', 'Callsign prefixes identify'),
    ('B.4', 'The national prefix for Spain is:',
     ['SP', 'EA', 'ES', 'SN'], 'B', 'Spain = EA; SP is Poland', 'Spain'),
    ('B.5', 'Which emergency centre of activity is used in Ireland on the 40 m band?',
     ['7.115 MHz', '7.050 MHz', '7.200 MHz', '7.000 MHz'], 'A', '7.115 MHz', 'Yes Yes 7.115'),
    ('B.5', 'Contests are NOT permitted on which band?',
     ['20 m', '80 m', '2 m', '12 m'], 'D', 'No contests on 60, 30, 17 or 12 m', '24.890–24.990'),
    ('B.5', 'The maximum power on the 160 m band above 1.850 MHz is:',
     ['400 W', '100 W', '10 W', '50 W'], 'C', '1.850–2.000 MHz: 10 W', '1.850–2.000'),
    ('B.5', 'Which band is secondary in Ireland?',
     ['2 m', '6 m (50 MHz)', '20 m', '70 cm'], 'B', 'Secondary: 5, 10, 50, 70 MHz', '50.000–52.000'),
    ('B.6', 'Contacts between radio amateurs are commonly referred to as:',
     ['Calls', 'Sessions', 'Links', 'QSOs'], 'D', 'QSO = a radio contact', 'commonly referred to as QSOs'),
    ('B.6', 'Self-discipline in amateur radio means that:',
     ['Operators voluntarily follow band plans and good practice; only the authorities enforce the law', 'Clubs fine their members', 'The IARU issues licences', 'Anyone can jam rule-breakers'], 'A',
     'The authority vs. self-discipline', 'Self-discipline'),
    ('B.6', 'The radio spectrum is best described as:',
     ['Owned by the first user', 'Owned by the IRTS', 'Reserved for contesters', 'A space shared by all radio amateurs, each with their own interests'], 'D',
     'Danger of conflict', 'space shared by all radio amateurs'),
    ('B.7', 'In the RST system, "S" stands for:',
     ['Speed', 'Signal strength', 'Selectivity', 'Sideband'], 'B', 'Readability, Strength, Tone', ('Strength', 368, 370)),
    ('B.7', 'Before calling on a frequency in Morse, you should send:',
     ['CQ immediately', 'SOS', 'QRL? DE (your call)', 'QRT'], 'C', 'Ask if the frequency is in use', 'QRL? DE EI5ABC'),
    ('B.7', 'In your transmissions, which call sign should come first?',
     ['The call sign of the station you are speaking to, followed by your own', 'Your own call sign first', 'Either, it does not matter', 'Only your own'], 'A',
     'ORDER OF CALL SIGNS', 'ORDER OF CALL SIGNS'),
    ('B.7', 'Irish regulations prescribe how often to identify during a QSO:',
     ['Every minute', 'Every 10 minutes always', 'Every 5 minutes on HF', 'They do not prescribe it, except in specific cases such as maritime mobile'], 'D',
     '/MM: at the beginning and end and every 30 minutes', 'Irish regulations do not prescribe'),
    ('B.7', 'You are asked "Is this frequency in use?" while you are listening to a weak station. You should:',
     ['Say nothing', 'Reply that the frequency is in use', 'Transmit a carrier', 'Change band'], 'B',
     'A frequency clear to one station may not be clear to another', 'frequency in use'),
    ('B.8', 'ITU Region 1 includes:',
     ['Europe, Africa, the Middle East and the former USSR', 'The Americas', 'Australia and Japan', 'Only the EU'], 'A', 'Ireland is in Region 1', ('Region 1', 314, 317)),
    ('B.8', 'The emission designator for SSB telephony with suppressed carrier is:',
     ['A1A', 'F3E', 'G3E', 'J3E'], 'D', 'J = SSB suppressed carrier, 3 = analogue, E = telephony', ('J3E', 316, 317)),
    ('B.9', 'The duration of a "short temporary visit" under CEPT arrangements is defined by each country, usually:',
     ['Up to 1 week', 'Up to 3 months', 'Up to 5 years', 'Unlimited'], 'B', 'Usually up to 3 months', 'usually up to 3 months'),
    ('B.9', 'Under CEPT, which regulations, frequencies, modes and power limits must be observed?',
     ['Those of your home country', 'Those of the ITU only', 'Those in force for the national CEPT-equivalent licence in the country being visited', 'Any you choose'], 'C',
     'The visited country\'s rules', 'COUNTRY BEING VISITED'),
    ('B.9', 'The national prefix for Poland is:',
     ['SP', 'PL', 'PO', 'OK'], 'A', 'Poland = SP', 'Poland'),
    ('B.10', 'Formal application and authorisation from ComReg is required for:',
     ['Changing band', 'Using a new antenna', 'Automatic or remote stations such as repeaters, beacons or Internet gateways', 'Using FT8'], 'C',
     'Additional authorisations', 'automatic or remote station licence'),
    ('B.10', 'Which of these must be recorded in the logbook?',
     ['The weather', 'The power level (dBW or W)', 'The other operator\'s name', 'The topic discussed'], 'B',
     'Logbook details', 'power level (dBW or W)'),
    ('B.10', 'On a vessel, an amateur station operating /MM must send its call sign:',
     ['At the beginning and end of each contact, or every 30 minutes, whichever is more frequent', 'Once a day', 'Only at the end', 'Every minute'], 'A',
     'Maritime mobile identification', 'intervals of 30 minutes'),
]
