import os
import re

DIR = os.path.dirname(os.path.abspath(__file__))

Q = {
    (1, 14): ('In the circuit shown, what current is drawn from the 12 V battery?',
              ['40 mA', '80 mA', '120 mA', '240 mA'], 'B',
              'R2 ∥ R3 = 50 Ω; total 150 Ω; I = 12/150 = 80 mA'),
    (1, 19): ('The block diagram shows a superheterodyne receiver. What is the block marked "X" most likely to be?',
              ['Beat frequency oscillator', 'IF filter (e.g. a crystal filter)', 'Low-pass filter for harmonics', 'Balanced modulator'], 'B',
              'The IF filter follows the mixer and sets the selectivity'),
    (1, 29): ('In the circuit shown, which meter is connected as an ammeter?',
              ['M2', 'M1', 'Both', 'Neither'], 'B',
              'M1 is in series with the load (ammeter); M2 is across it (voltmeter)'),
    (2, 15): ('L and C in the circuit shown are resonant at frequency f₀. Ignoring losses, the circuit:',
              ['Passes signals at f₀ readily and attenuates others (band-pass)', 'Blocks signals at f₀',
               'Passes all frequencies equally', 'Acts as a low-pass filter'], 'A',
              'Series LC in series with the signal path is an acceptor, so it acts as a band-pass'),
    (2, 24): ('The figure shows the horizontal (plan view) radiation pattern of an antenna in free space. It is typical of:',
              ['A quarter-wave vertical', 'A 3-element Yagi', 'An isotropic radiator', 'A horizontal half-wave dipole'], 'D',
              'Figure-of-eight, maximum broadside to the wire'),
    (2, 30): ('The oscilloscope is set to 2 V/div vertical and 1 ms/div horizontal. What is the peak-to-peak voltage of the signal?',
              ['8 V', '4 V', '2.83 V', '16 V'], 'A',
              '4 divisions peak-to-peak × 2 V/div = 8 V'),
    (3, 14): ('In the circuit shown, what current flows?',
              ['100 mA', '300 mA', '33 mA', '900 mA'], 'A',
              'R = 3 × 30 = 90 Ω; I = 9/90 = 0.1 A'),
    (3, 20): ('The block diagram shows a CW transmitter. What is the stage marked "X"?',
              ['Mixer', 'Product detector', 'Buffer amplifier', 'Frequency discriminator'], 'C',
              'A buffer isolates the VFO from load changes in later stages'),
    (3, 30): ('The figure shows the RF envelopes of two CW transmissions on an oscilloscope. Which is likely to cause key clicks?',
              ['Trace 2', 'Both', 'Neither', 'Trace 1'], 'D',
              'Trace 1 has abrupt rise and fall times'),
    (4, 15): ('The figure shows the voltage V (solid) and current I (dashed) in an AC circuit. What kind of circuit is it?',
              ['A pure resistance', 'A pure inductance', 'A series LC circuit at resonance', 'A pure capacitance'], 'D',
              'I peaks a quarter cycle before V: the current leads, so the circuit is capacitive'),
    (4, 17): ('In the superheterodyne receiver block diagram, what is the block marked "X"?',
              ['Detector', 'IF amplifier', 'Mixer', 'AGC'], 'C',
              'X combines the RF and local oscillator signals: the mixer'),
    (4, 24): ('In the station shown, the ATU has been adjusted until meter M reads an SWR of 1:1. What does this tell you?',
              ['The SWR on the coax to the antenna is also 1:1', 'The antenna is resonant',
               'There is no loss in the coax',
               'The transmitter sees a matched load, but the SWR on the coax between the ATU and the antenna may still be high'], 'D',
              'The ATU only matches on its transmitter side'),
    (5, 14): ('L and C in the circuit shown are resonant at frequency f₀. Ignoring losses, signals at f₀:',
              ['Pass through readily', 'Pass only above f₀', 'Are blocked (the parallel LC acts as a rejector)', 'Are doubled in frequency'], 'C',
              'Parallel LC in series with the signal path = rejector (band-stop)'),
    (5, 19): ('The block diagram shows an SSB transmitter. What is the block marked "X"?',
              ['Balanced modulator', 'Frequency multiplier', 'Discriminator', 'SWR meter'], 'A',
              'The balanced modulator combines the speech and the carrier, suppressing the carrier'),
    (5, 30): ('The oscilloscope trace shows the RF output of an AM transmitter. It shows:',
              ['Overmodulation', 'Correct modulation (below 100%)', 'An unmodulated carrier', 'An FM signal'], 'A',
              'The envelope is pinched to zero with flat gaps'),
    (6, 15): ('The graph shows the frequency response of a filter. It is a:',
              ['High-pass filter', 'Low-pass filter', 'Band-pass filter', 'Band-stop filter'], 'B',
              'Passes below fc, attenuates above'),
    (6, 22): ('The figure shows the distribution of current and voltage along a resonant half-wave dipole. Curve 2 (dashed) represents:',
              ['Current', 'Radiated power', 'Feeder loss', 'Voltage'], 'D',
              'Voltage is maximum at the ends; current (curve 1) is maximum at the centre'),
    (6, 29): ('You want to measure the current through resistor R. At which position should the ammeter be connected?',
              ['Y', 'Z', 'Either Y or Z', 'X'], 'D',
              'An ammeter goes in series: position X'),
    (7, 14): ('In the circuit shown, what current is drawn from the 30 V battery?',
              ['0.1 A', '0.3 A', '0.9 A', '30 mA'], 'B',
              '300/3 = 100 Ω; I = 30/100 = 0.3 A'),
    (7, 24): ('Using the figure, what is the ERP?',
              ['23 dBW (200 W)', '20 dBW (100 W)', '14 dBW (25 W)', '26 dBW (400 W)'], 'B',
              '17 − 3 + 6 = 20 dBW = 100 W'),
    (7, 30): ('In the station shown, the SWR meter measures:',
              ['The SWR on the feeder to the antenna', 'The SWR between the transmitter and the ATU',
               'The mains voltage', 'The antenna gain'], 'A',
              'It measures where it is placed: the feeder side of the ATU'),
    (8, 14): ('What is the total resistance between terminals A and B?',
              ['500 Ω', '300 Ω', '200 Ω', '150 Ω'], 'C',
              '100 + (200 ∥ 200 = 100) = 200 Ω'),
    (8, 19): ('The block diagram shows an FM receiver. What is the block marked "X"?',
              ['Discriminator (FM demodulator)', 'Product detector', 'Beat frequency oscillator', 'Balanced modulator'], 'A',
              'The limiter is followed by the FM discriminator'),
    (8, 24): ('The figure shows a 3-element Yagi from above; element 2 is fed. In which direction is the maximum radiation?',
              ['Towards element 1', 'Perpendicular to the boom', 'Equally in all directions', 'Towards element 3'], 'D',
              '1 = reflector (longest), 3 = director (shortest): beam towards the director'),
    (9, 15): ('The circuit shown is a:',
              ['High-pass filter', 'Band-stop filter', 'Low-pass (pi) filter', 'Band-pass filter'], 'C',
              'The series L passes low frequencies; the shunt Cs short high frequencies to ground'),
    (9, 17): ('The figure shows part of an SDR transmitter using direct digital synthesis. What is block "X"?',
              ['ADC', 'BFO', 'Mixer', 'DAC'], 'D',
              'NCO + DAC = DDS, followed by a reconstruction filter'),
    (9, 24): ('The figure shows the horizontal radiation pattern of an antenna. It is typical of:',
              ['A 3-element Yagi', 'A horizontal half-wave dipole', 'A quarter-wave vertical ground plane', 'A parabolic dish'], 'C',
              'Omnidirectional in the horizontal plane'),
    (10, 14): ('In the circuit shown, the ammeter reads 10 mA. What power is dissipated in the resistor?',
               ['10 W', '0.1 W', '1 W', '0.01 W'], 'B',
               'P = I²R = 0.01² × 1000 = 0.1 W'),
    (10, 21): ('You want to connect a 300 Ω folded dipole to 75 Ω coax as shown. What should block "X" be?',
               ['A 1:1 balun', 'A 9:1 unun', 'A 4:1 balun', 'Nothing — connect directly'], 'C',
               '300:75 = 4:1, and the balun also converts balanced to unbalanced'),
    (10, 30): ('The oscilloscope is set to 1 V/div vertical and 0.2 ms/div horizontal. What is the frequency of the signal?',
               ['1 Hz', '200 Hz', '1 MHz', '1 kHz'], 'D',
               'One cycle = 5 div × 0.2 ms = 1 ms, so f = 1 kHz'),
}

for (s, q), (text, opts, ans, expl) in Q.items():
    path = f'{DIR}/practice_exams/HAREC_Practice_Exam_Set_{s:02d}.md'
    md = open(path).read()
    fig = f'figures/set{s:02d}_q{q}.svg'
    block = (f'**{q}.** {text}\n\n![Figure for question {q}]({fig})\n\n' +
             ''.join(f'- {l}) {o}\n' for l, o in zip('ABCD', opts)))
    md, n = re.subn(rf'\*\*{q}\.\*\* .*?\n(?:\n!\[.*\n\n)?(?:- .*\n){{4}}', lambda m: block, md, count=1)
    assert n == 1, (s, q, 'question')
    md, n = re.subn(rf'^\| {q} \| [A-D] \| .*$', f'| {q} | {ans} | {expl} |', md, count=1, flags=re.M)
    assert n == 1, (s, q, 'key')
    open(path, 'w').write(md)
print('updated', len(Q), 'questions')
