TITLE = 'Electrical and Electronic Principles'
SECTION = 'A.3'
PAGES = (12, 27)
TOPICS = {
    '3.1': 'The Nature of Electricity',
    '3.2': 'Dimensions, Units, and Metric Prefixes',
    '3.3': 'Current',
    '3.4': 'Sources of Electricity and Electromotive Force',
    '3.5': 'Voltage',
    '3.6': 'Difference Between Electromotive Force and Voltage',
    '3.7': 'Voltage and Current in Series and Parallel Circuits',
    '3.8': 'Resistance',
    '3.9': "Ohm's Law",
    '3.10': 'Electric Power and Energy',
}

QUESTIONS = [
    ('3.1', 'Which subatomic particle carries a negative electric charge?', ['Proton', 'Neutron', 'Electron', 'Photon'], 'C', 'The proton is positive (+) and the electron is negative (−)', 'the electron has a negative electric charge'),
    ('3.1', 'In a metal conductor such as copper, the primary charge carriers are:', ['Electrons', 'Neutrons', 'Protons', 'Holes'], 'A', 'In metals, electrons move from atom to atom and form the current', 'Electrons are, therefore, the primary charge carriers in metal conductors'),
    ('3.1', 'An electric current is best described as:', ['The rate at which energy is used', 'The pressure that pushes charges', 'The opposition to the flow of charge', 'A flow of charge carriers, such as electrons'], 'D', 'A flow of charge carriers such as electrons in a metal is an electric current', 'flow of charge carriers, like electrons in a metal, is known as electric current'),
    ('3.2', 'The SI unit symbol for frequency is:', ['hz', 'Hz', 'HZ', 'hZ'], 'B', 'Hertz is written Hz: the H must be a capital', '1 Hz is correct, but 1 hz is incorrect'),
    ('3.2', 'Which of these is the correct unit symbol for the second?', ['S', 'Sc', 'sec', 's'], 'D', 'Lowercase s is the second; uppercase S is the siemens', 'Lowercase s is correct, while uppercase S is not'),
    ('3.2', 'Which unit is used for inductance?', ['Farad (F)', 'Henry (H)', 'Ohm (Ω)', 'Hertz (Hz)'], 'B', 'Inductance L is measured in henry, H; capacitance in farad', ('henry', 14, 14)),
    ('3.2', 'Reactance and impedance are both measured in:', ['Farads', 'Henries', 'Ohms', 'Siemens'], 'C', 'Resistance, reactance and impedance all use the ohm, Ω', ('Inductive Reactance', 14, 14)),
    ('3.2', 'The metric prefix µ (micro) means a factor of:', ['10⁻⁶', '10⁻¹²', '10⁻⁹', '10⁻³'], 'A', 'Micro = one millionth = 10⁻⁶', 'One millionth'),
    ('3.2', 'Which prefix symbol stands for one thousand million (10⁹)?', ['G', 'M', 'k', 'm'], 'A', 'Giga, G, is 10⁹; mega, M, is 10⁶', 'One thousand million'),
    ('3.2', 'Which of these is written correctly for one thousand hertz?', ['1 KHz', '1 khz', '1 kHz', '1 KHZ'], 'C', 'Kilo is a lowercase k and hertz is Hz, so kHz', 'kHz is correct, while KHz is incorrect'),
    ('3.2', 'What is 1.5 kΩ + 750 Ω?', ['751.5 Ω', '1650 Ω', '2.25 Ω', '2250 Ω'], 'D', 'Convert to the same prefix first: 1500 Ω + 750 Ω = 2250 Ω', '1500 Ω + 750 Ω = 2250 Ω'),
    ('3.2', 'What is 500 mV + 2.5 V?', ['502.5 V', '3 V', '2.55 V', '7.5 V'], 'B', '500 mV = 0.5 V; 0.5 + 2.5 = 3 V', '0.5 V + 2.5 V = 3 V'),
    ('3.3', 'By convention, "conventional current" is said to flow:', ['From the negative to the positive terminal', 'Only in AC circuits', 'From the positive to the negative terminal', 'In both directions at once'], 'C', 'Electrons flow from − to +, but conventional current is said to flow from + to −', 'flows from the positive to the negative terminals'),
    ('3.3', 'Which of these materials is an insulator?', ['Salt water', 'Mica', 'Carbon', 'Aluminium'], 'B', 'Glass, Perspex, rubber, mica, most plastics, oil, air and distilled water are insulators', 'rubber, mica, most plastics'),
    ('3.3', 'Which of these is a good conductor?', ['Silver', 'Glass', 'Dry air', 'Distilled water'], 'A', 'Almost all metals are good conductors, including silver, copper and gold', 'silver, copper, gold, aluminium'),
    ('3.3', 'The best-known semiconductor material is:', ['Mercury', 'Copper', 'Mica', 'Silicon'], 'D', 'Silicon is the best-known semiconductor', 'The best-known example of a semiconductor'),
    ('3.3', 'What is special about the current through a p-n junction?', ['It does not depend on voltage', 'It flows only in AC circuits', 'It depends on the direction in which the current wants to flow', 'It is always zero'], 'C', 'A p-n junction conducts according to the direction of the current, which is how a diode works', 'depends not only on the voltage but also on the direction'),
    ('3.3', 'The mains supply in an Irish domestic socket has a frequency of:', ['50 Hz', '60 Hz', '100 Hz', '230 Hz'], 'A', 'Irish domestic AC completes 50 cycles per second', 'domestic AC has a frequency of 50 Hz'),
    ('3.3', 'Direct current (DC) is current that:', ['Reverses direction 50 times a second', 'Always has a constant value', 'Can only come from the mains', 'Flows in one direction only'], 'D', 'DC flows in one direction; its amount may still change', 'travels only in one direction'),
    ('3.4', 'Why does the terminal voltage of a real battery fall when a load is connected?', ['Because the emf increases', 'Because of its internal resistance', 'Because AC is produced', 'Because the load generates voltage'], 'B', 'The internal resistance causes a voltage drop when current is drawn', 'causes a voltage drop when connected to a load'),
    ('3.4', 'Two 6 V batteries are connected in series (positive of one to negative of the other). The total voltage is:', ['6 V', '3 V', '36 V', '12 V'], 'D', 'In series the total source voltage is the sum of the individual voltages', 'the total source voltage is the sum of the individual voltages'),
    ('3.4', 'Connecting two identical batteries in parallel:', ['Keeps the voltage the same but increases the current capacity', 'Doubles the voltage', 'Halves the voltage', 'Creates an AC supply'], 'A', 'In parallel each source has the same voltage, and the current drain is shared', 'the current capacity is increased'),
    ('3.4', 'Why is caution needed when connecting voltage sources in parallel?', ['Their voltages add up', 'Their internal resistance becomes zero', 'Small differences in terminal voltage can cause a circulating current between them', 'They stop supplying current'], 'C', 'Different terminal voltages drive a circulating current between the sources', 'may cause a circulating current between the sources'),
    ('3.4', 'The current that flows when the two terminals of a voltage source are joined by a wire is limited by:', ['The load resistance', 'The internal resistance of the source', 'The voltmeter', 'Nothing at all'], 'B', 'The internal resistance limits the short circuit current', 'limit the total current to the short circuit current'),
    ('3.5', 'The potential difference (PD) between two points in a circuit is also called:', ['Current', 'Resistance', 'Voltage', 'Power'], 'C', 'The PD between any two points is the voltage', 'between any two points in the circuit is known as the voltage'),
    ('3.6', 'The emf of a source is equal to its terminal voltage when:', ['The source is short-circuited', 'An AC load is connected', 'The maximum current flows', 'No current is flowing'], 'D', 'Emf equals the terminal PD when no current flows', 'equal to the terminal source PD when no current flows'),
    ('3.6', 'A voltmeter used to measure emf or PD must have:', ['A very low internal resistance', 'A high internal resistance', 'Its own battery', 'A resistance equal to the load'], 'B', 'A high internal resistance stops the meter drawing significant current', 'must have a high internal resistance'),
    ('3.7', 'In a series circuit:', ['The same current flows through every component', 'The voltage across every component is the same', 'The current divides between the components', 'Each component has its own source'], 'A', 'The same current flows through each component of a series circuit', 'The same current flows through each component of a series connected circuit'),
    ('3.7', 'A 12 V battery feeds two resistors in series. 8 V is measured across the first. What is the voltage across the second?', ['20 V', '8 V', '4 V', '12 V'], 'C', 'The voltages across the components add up to the source voltage: 12 − 8 = 4 V', 'the source voltage in a series circuit is equal to the sum of the individual voltages'),
    ('3.7', 'In a parallel circuit with two branches drawing 2 A and 3 A, the current from the source is:', ['1 A', '5 A', '6 A', '2.5 A'], 'B', 'The source current equals the sum of the branch currents', 'equal to the sum of the remaining branch currents'),
    ('3.7', 'In a parallel circuit, the voltage across each branch is:', ['The same in every branch', 'Different in each branch', 'Zero', 'Shared in proportion to resistance'], 'A', 'All branches of a parallel circuit have the same voltage', 'All branches of a parallel connected circuit have the same voltage'),
    ('3.7', 'The way current and voltage are distributed in a circuit is described by:', ['The inverse square law', "Lenz's law", "Faraday's law", "Kirchhoff's current and voltage laws"], 'D', "Kirchhoff's laws describe current and voltage distribution", 'Kirchhoff s current and voltage laws'),
    ('3.8', 'Resistance is:', ['The rate of flow of charge', 'The opposition to the flow of current', 'The pressure that drives current', 'The energy stored in a circuit'], 'B', 'Resistance is the opposition to the flow of current, measured in ohms (Ω)', 'is the opposition to the flow of the current'),
    ('3.9', "According to Ohm's law, if the resistance stays the same and the voltage is doubled, the current:", ['Halves', 'Stays the same', 'Doubles', 'Quadruples'], 'C', 'Current is directly proportional to voltage', 'current is directly proportional to voltage'),
    ('3.9', 'A 20 V battery is connected across a 100 Ω resistor. What current flows?', ['0.2 A', '2 A', '5 A', '2000 A'], 'A', 'I = V/R = 20/100 = 0.2 A (200 mA)', 'This can be also expressed as 200 mA'),
    ('3.9', 'A current of 0.5 A flows through a 24 Ω resistor. The voltage across it is:', ['48 V', '0.02 V', '24.5 V', '12 V'], 'D', 'V = I × R = 0.5 × 24 = 12 V', ('Ohm’s law formulae', 22, 22)),
    ('3.9', 'If the voltage is kept constant and the resistance increases, the current:', ['Increases', 'Decreases', 'Stays the same', 'Reverses'], 'B', 'Current is inversely proportional to resistance', 'current is inversely proportional to resistance'),
    ('3.10', 'Power is the rate at which:', ['Voltage rises', 'Charge is stored', 'Resistance changes', 'Energy is transferred or used'], 'D', 'Power tells us how fast energy is transferred or used', 'how fast energy is transferred or used'),
    ('3.10', 'A 20 V source drives 0.2 A through a resistor. The power dissipated is:', ['100 W', '0.01 W', '4 W', '40 W'], 'C', 'P = V × I = 20 × 0.2 = 4 W', 'the power transferred in that circuit will have to be dissipated'),
    ('3.10', 'A current of 2 A flows through a 10 Ω resistor. The power dissipated is:', ['40 W', '20 W', '5 W', '200 W'], 'A', 'P = I²R = 2 × 2 × 10 = 40 W', 'if you know the current I in amps, but you do not know the voltage'),
    ('3.10', 'A 50 Ω dummy load has 100 V across it. The power it dissipates is:', ['5000 W', '2 W', '500 W', '200 W'], 'D', 'P = V²/R = 10 000/50 = 200 W', 'if you know the voltage in volts, but you do not know the current'),
    ('3.10', 'A 12 V battery is rated at 8 A⋅h. How much energy can it store?', ['96 Wh', '1.5 Wh', '20 Wh', '8 kWh'], 'A', 'Energy = 8 A⋅h × 12 V = 96 Wh (0.096 kWh)', '8 A h × 12 V = 96 Wh'),
    ('3.10', 'An 8 A⋅h battery can supply approximately:', ['8 A for 8 hours', '1 A for 1 hour', '4 A for 2 hours', '16 A for 2 hours'], 'C', '8 A⋅h = 8 A for 1 h, 4 A for 2 h, 16 A for 30 min', '4 A for 2 hours'),
    ('3.10', 'A 1000 W linear amplifier is used for 1 hour. How much energy does it use?', ['1 Wh', '1 kWh', '1 MWh', '1000 kWh'], 'B', 'W = P × t = 1000 W × 1 h = 1000 Wh = 1 kWh', 'which is equivalent to 1 kWh'),
    ('3.7', 'In the circuit shown, the voltmeter across R1 reads 8 V. What is the voltage across R2?', ['20 V', '8 V', '4 V', '12 V'], 'C', 'In a series circuit the voltages add up to the source voltage: 12 − 8 = 4 V', 'the source voltage in a series circuit is equal to the sum of the individual voltages', 'ch03_series'),
    ('3.7', 'In the circuit shown, the branch ammeters read 2 A and 3 A. What current I does the battery supply?', ['5 A', '1 A', '6 A', '2.5 A'], 'A', 'The current entering a junction equals the sum of the branch currents: 2 + 3 = 5 A', 'equal to the sum of the remaining branch currents', 'ch03_parallel'),
    ('3.9', 'What does the ammeter in the circuit shown read?', ['2 A', '20 mA', '5 A', '200 mA'], 'D', 'I = V/R = 20 V / 100 Ω = 0.2 A = 200 mA', 'This can be also expressed as 200 mA', 'ch03_ohm'),
    ('3.4', 'What does the voltmeter connected across the two batteries shown read?', ['6 V', '12 V', '0 V', '3 V'], 'B', 'Batteries in series add their voltages: 6 + 6 = 12 V', 'the total source voltage is the sum of the individual voltages', 'ch03_batteries'),
]
