TITLE = 'Alternating Current and Sinusoidal Signals'
SECTION = 'A.3'
PAGES = (38, 47)
TOPICS = {
    '5.1': 'Sinusoidal Signals',
    '5.1.1': 'Amplitude',
    '5.1.2': 'Period and Frequency',
    '5.1.3': 'Wavelength and Frequency',
    '5.1.4': 'Instantaneous and Average Values',
    '5.1.5': 'rms, Effective Voltage, Peak-to-Peak Voltage, Power',
    '5.2': 'Alternating Current',
    '5.3': 'Phase',
    '5.4': 'Harmonics',
    '5.5': 'Modulated Sinusoidal Signals',
}

QUESTIONS = [
    ('5.1', 'A plot with time on its horizontal axis is called a plot in the:', ['Frequency domain', 'Time domain', 'Spatial domain', 'Phase domain'], 'B', 'Plots that show time on the horizontal axis are time-domain plots', 'are also known as plots in the time domain'),
    ('5.1', 'At what angle does a sine wave that starts at zero reach its positive peak?', ['270°', '180°', '90°', '45°'], 'C', 'Zero at 0°, peak at 90°, zero at 180°, negative peak at 270°', 'reaching the peak amplitude at 90'),
    ('5.1', 'To describe a sinusoidal signal completely, you need to know its:', ['Wavelength and colour', 'Phase only', 'Average value only', 'Amplitude and its period or frequency'], 'D', 'Amplitude plus period or frequency; everything else follows from the sine shape', 'you need to know its: amplitude and its period or its frequency'),
    ('5.1.1', 'The amplitude (peak voltage) of a sinusoidal signal is:', ['The maximum voltage in either direction of flow', 'The voltage between the positive and negative peaks', 'The average voltage of a whole cycle', 'The rms voltage'], 'A', 'Amplitude, VPEAK or VMAX, is the maximum voltage in either direction', 'is the maximum voltage in either direction of the flow'),
    ('5.1.2', 'A signal has a period of 1 ms. What is its frequency?', ['1 kHz', '100 Hz', '1 Hz', '1 MHz'], 'A', 'f = 1/period = 1/0.001 s = 1000 Hz', ('If you know the frequency, you can easily calculate the period', 40, 40)),
    ('5.1.2', 'A frequency of 1 Hz means:', ['One volt per second', 'One cycle per minute', 'One cycle per second', 'One metre per second'], 'C', '1 Hz is exactly one cycle in one second', '1 Hz is a signal whose period is exactly 1 second'),
    ('5.1.2', 'A signal with an identifiable period is called:', ['A random signal', 'A DC signal', 'A noise signal', 'A periodic signal'], 'D', 'Signals with an identifiable period are periodic; all sinusoids are periodic', 'All sinusoidal signals are periodic'),
    ('5.1.3', 'The wavelength of a signal is:', ['The time taken by one cycle', 'The distance it travels in one period', 'The height of the wave', 'The number of cycles per second'], 'B', 'Wavelength is the distance travelled in one period, e.g. crest to crest', 'that the signal would propagate in one period'),
    ('5.1.3', 'Radio waves in a vacuum travel at approximately:', ['300 000 m/s', '3 000 000 m/s', '300 000 000 m/s', '30 000 000 000 m/s'], 'C', 'The speed of light, c, is about 300 000 000 m/s', 'approximately equal to 300 000 000 m/s'),
    ('5.1.3', 'What is the wavelength of a 50 MHz signal?', ['0.6 m', '6 m', '60 m', '15 m'], 'B', 'λ = 300/f(MHz) = 300/50 = 6 m', 'what is the wavelength of the 50 MHz frequency'),
    ('5.1.3', 'What frequency corresponds to a wavelength of 30 m?', ['1 MHz', '9 MHz', '10 MHz', '90 MHz'], 'C', 'f(MHz) = 300/λ = 300/30 = 10 MHz', 'What is the frequency f of the 30 m wavelength'),
    ('5.1.3', 'What is the approximate wavelength of a 3650 kHz signal?', ['8.2 m', '1.1 km', '820 m', '82 m'], 'D', 'Convert to MHz first: 3.65 MHz; λ = 300/3.65 ≈ 82 m', 'make sure to convert it to MHz'),
    ('5.1.3', 'The distance between two successive crests of a wave is its:', ['Wavelength', 'Amplitude', 'Period', 'Peak-to-peak value'], 'A', 'Wavelength is the distance between successive crests', 'the distance between two successive crests of the wave'),
    ('5.1.4', 'The average value of one half-cycle of a sine wave is about:', ['0.636 × VPK', '0.707 × VPK', '1.414 × VPK', '2.828 × VPK'], 'A', 'VAVG = 0.636 × VPK for a half-cycle', ('The average value of each half-cycle', 42, 42)),
    ('5.1.4', 'The average value of a complete cycle of a sine wave is:', ['0.636 × VPK', 'Zero', '0.707 × VPK', 'Equal to the peak value'], 'B', 'The positive and negative halves cancel, so the average over a whole cycle is zero', 'The average value of a whole cycle of a sinusoidal signal is always zero'),
    ('5.1.5', 'A sine wave has a peak voltage of 100 V. Its rms voltage is about:', ['63.6 V', '70.7 V', '141.4 V', '200 V'], 'B', 'VRMS = 0.707 × VPK', 'The abbreviation rms'),
    ('5.1.5', 'The voltage normally shown by an AC voltmeter is the:', ['Peak voltage', 'Peak-to-peak voltage', 'Average voltage of a whole cycle', 'rms (effective) voltage'], 'D', 'AC voltmeters normally indicate the effective, rms, value', 'This is also the voltage that is normally indicated by an AC voltmeter'),
    ('5.1.5', 'The abbreviation rms stands for:', ['Radio mean signal', 'Rated maximum supply', 'Root mean square', 'Relative modulation strength'], 'C', 'rms = root mean square', 'stands for root mean square'),
    ('5.1.5', 'A sine wave measures 10 V rms. Its peak-to-peak voltage is about:', ['14.1 V', '20 V', '7.07 V', '28.3 V'], 'D', 'VPP = 2.828 × VRMS', ('peak-to-peak', 43, 43)),
    ('5.1.5', 'A 500 Ω resistor is connected to the 230 V rms mains. How much power does it dissipate?', ['0.46 W', '105.8 W', '115 W', '211.6 W'], 'B', 'P = VRMS²/R = 230²/500 ≈ 105.8 W', '= 105.8 W'),
    ('5.1.5', 'Why is the rms value so useful?', ['It makes AC calculations, such as power, as easy as for DC', 'It is always zero', 'It equals the peak-to-peak voltage', 'It removes harmonics'], 'A', "Using VRMS lets you apply Ohm's law and the power formulas as for DC", 'makes other AC calculations as easy as for DC'),
    ('5.2', 'The peak voltage of the Irish 230 V rms mains supply is about:', ['163 V', '230 V', '325 V', '650 V'], 'C', 'VPK = 1.414 × 230 ≈ 325 V', ('1.414 × 230 V = 325 V', 44, 44)),
    ('5.2', 'The period of the 50 Hz mains supply is:', ['2 ms', '20 ms', '50 ms', '200 ms'], 'B', '1 s / 50 = 0.02 s = 20 ms', 'period is 1 s/50 = 0.02 s = 20 ms'),
    ('5.2', 'The peak-to-peak voltage of the Irish mains supply is about:', ['230 V', '325 V', '460 V', '650 V'], 'D', 'VPP = 2.828 × 230 ≈ 650 V', ('2.828 × 230 V = 650 V', 44, 44)),
    ('5.3', 'Two signals of the same frequency cross the zero line a quarter of a cycle apart. Their phase difference is:', ['360°', '180°', '90°', '45°'], 'C', 'One cycle is 360°, so ¼ cycle is 90°', 'by 90 or ¼ cycle'),
    ('5.3', 'Signal X crosses zero 90° before signal Y. We say that:', ['X leads Y by 90°', 'X lags Y by 90°', 'X and Y are in phase', 'X has twice the frequency of Y'], 'A', 'The one that crosses first leads; the other lags', 'Blue leads the red by 90'),
    ('5.4', 'A harmonic is a signal whose frequency is:', ['Slightly different from another signal', 'Unrelated to any other signal', 'Always half of another signal', "An exact multiple of another signal's frequency"], 'D', 'A harmonic is at an exact multiple of the fundamental', 'A wave whose frequency is an exact multiple of another is called a harmonic'),
    ('5.4', 'The second harmonic of a 7.1 MHz signal is at:', ['3.55 MHz', '7.1 MHz', '14.2 MHz', '21.3 MHz'], 'C', 'Second harmonic = 2 × fundamental', 'has a frequency that is twice that of the original signal'),
    ('5.4', 'The fundamental frequency is also known as the:', ['First harmonic', 'Zero harmonic', 'Second harmonic', 'Carrier harmonic'], 'A', 'The fundamental is the first harmonic', 'fundamental frequency or as the first harmonic'),
    ('5.4', 'Why do excessive harmonics from a transmitter matter?', ['They cause interference and may put signals outside the allowed bands', 'They improve range', 'They reduce the SWR', 'They only affect the receiver'], 'A', 'Unwanted harmonics cause interference and may be illegal out-of-band emissions', 'may even cause you to transmit outside of the allowed bands'),
    ('5.5', 'A pure, unmodulated sine wave used as a carrier:', ['Carries speech', 'Carries no information on its own', 'Contains many harmonics', 'Is always at 50 Hz'], 'B', 'A pure sine wave carries no information other than its presence', 'would carry no information'),
    ('5.5', 'The process of impressing information, such as speech, on a carrier is called:', ['Rectification', 'Quantisation', 'Resonance', 'Modulation'], 'D', 'Impressing information on the carrier is modulation', 'This process is known as modulation'),
    ('5.1.5', 'What is the peak-to-peak voltage of the signal shown on the oscilloscope?', ['6 V', '3 V', '12 V', '24 V'], 'C', 'Each peak is 3 divisions × 2 V = 6 V from the centre, so peak-to-peak is 12 V', ('peak-to-peak', 43, 43), 'ch05_scope'),
    ('5.1.2', 'What is the frequency of the signal shown on the oscilloscope?', ['500 Hz', '2 kHz', '250 Hz', '5 kHz'], 'A', 'One cycle spans 4 divisions × 0.5 ms = 2 ms, so f = 1/2 ms = 500 Hz', ('If you know the frequency, you can easily calculate the period', 40, 40), 'ch05_scope'),
    ('5.3', 'Compare the two signals shown. Which statement is true?', ['They are in phase', 'A lags B by 180°', 'A and B have different frequencies', 'A leads B by 90°'], 'D', 'A reaches its peak a quarter of a cycle (90°) before B', 'by 90 or ¼ cycle', 'ch05_phase'),
    ('5.1.3', 'In the figure, the distance X between two successive crests of the wave is its:', ['Amplitude', 'Wavelength', 'Frequency', 'Period'], 'B', 'The wavelength is the distance between two successive crests', 'the distance between two successive crests of the wave', 'ch05_crests'),
    ('5.4', 'The spectrum shows a transmitter on 7.1 MHz. The line at 14.2 MHz is the:', ['Second harmonic', 'Image frequency', 'Third harmonic', 'Intermediate frequency'], 'A', 'A frequency twice the fundamental is the second harmonic; 21.3 MHz is the third', 'has a frequency that is twice that of the original signal', 'ch05_harmonics'),
]
