TITLE = 'Measurements'
SECTION = 'A.8'
PAGES = (272, 281)
TOPICS = {
    '17.1': 'Multimeter, Ammeter, Ohmmeter, Voltmeter',
    '17.2': 'SWR and Power',
    '17.3': 'Oscilloscope',
    '17.4': 'RF Envelope',
    '17.5': 'Spectrum Analyser',
    '17.6': 'Signal Generator',
    '17.7': 'Frequency Counter',
    '17.8': 'Field Strength Meter',
    '17.9': 'Antenna Analyser',
    '17.10': 'Dummy Load',
}

QUESTIONS = [
    ('17.1', 'Which instrument measures current, resistance and voltage?', ['Multimeter', 'Ammeter', 'Oscilloscope', 'Frequency counter'], 'A', 'A multimeter (multi-range meter) measures current, resistance and voltage', 'also known as the multirange meter'),
    ('17.1', 'To measure voltage, the meter is connected:', ['In series with the circuit', 'Only to the earth', 'In parallel (across) the points being measured', 'Through a capacitor'], 'C', 'A voltmeter is connected across the circuit', 'the meter is connected across the points, i.e., in parallel with the circuit'),
    ('17.1', 'An ideal voltmeter should have:', ['A very low resistance', 'A very high impedance (resistance)', 'Zero impedance', 'An inductive impedance'], 'B', 'A high resistance draws little current, so it does not disturb the voltage measured', 'An ideal voltmeter should have a high impedance'),
    ('17.1', 'To measure current, the meter is connected:', ['To the antenna', 'In parallel with the supply', 'Across the load', 'In series with the circuit'], 'D', 'The current must flow through the ammeter, so it goes in series', 'the meter is connected in series with the circuit where the current is to be determined'),
    ('17.1', 'An ideal ammeter should have:', ['A high resistance', 'A capacitive impedance', 'A low impedance (resistance)', 'An infinite impedance'], 'C', 'Low resistance avoids affecting the current measured', 'An ideal ammeter should have a low impedance'),
    ('17.1', 'Why must resistance not be measured in a live circuit?', ['It would reduce the resistance', 'The ohmmeter applies its own voltage to the component', 'It is only possible with AC', 'The meter needs mains power'], 'B', 'Ohmmeters use an internal battery; measure with the circuit unpowered', 'measurements should not be made in live circuits'),
    ('17.2', 'An SWR meter shows 120 W forward and 20 W reflected power. The net power to the antenna is:', ['140 W', '120 W', '100 W', '20 W'], 'C', 'Net power = forward − reflected = 100 W', 'the net power going to the antenna is 100 W'),
    ('17.2', 'Another name for an SWR meter is:', ['Reflectometer', 'Ohmmeter', 'Frequency counter', 'Dummy load'], 'A', 'Also called an SWR bridge or reflectometer', 'or a reflectometer'),
    ('17.2', 'An SWR meter shows an infinite SWR. You should:', ['Increase power', 'Add a longer coax', 'Ignore it', 'Turn the transmitter off immediately and investigate'], 'D', 'Infinite SWR indicates a serious fault such as an open or short circuit', 'the transmitter should be immediately turned off'),
    ('17.2', 'On a cross-needle SWR meter, the SWR is read:', ['From the forward needle only', 'From a separate display', 'From the reflected needle only', 'Where the two needles intersect'], 'D', 'The crossing point of the forward and reflected needles gives the SWR', 'The intersection of the crossing needles gives the SWR'),
    ('17.2', 'Because an SWR meter contains diodes, it should be placed:', ['After the low-pass filter', 'Before any final low-pass filter', 'At the antenna feed point only', 'Inside the transceiver'], 'B', 'Diodes can create harmonics, so the low-pass filter goes after the meter', 'it should be placed before any final low-pass filters'),
    ('17.3', 'An oscilloscope displays signals in the:', ['Time domain', 'Frequency domain', 'Impedance domain', 'Power domain only'], 'A', 'Horizontal axis is time; vertical is amplitude (voltage)', 'for displaying electrical waveforms in the time domain'),
    ('17.3', 'On an oscilloscope, the vertical axis usually shows:', ['Frequency', 'Time', 'Amplitude (voltage)', 'Phase'], 'C', 'Vertical: amplitude; horizontal: time', 'The vertical axis shows the amplitude of the signal'),
    ('17.4', "The outline of a signal's time-domain plot, used to diagnose overmodulation, is the:", ['Spectrum', 'RF envelope', 'Waterfall', 'Smith chart'], 'B', 'The RF envelope can be viewed on an oscilloscope', 'is the outline, i.e., the envelope, of a time domain plot of a signal'),
    ('17.4', 'The two-tone test is used to check an SSB transmitter for:', ['Amplitude linearity and overmodulation', 'Frequency accuracy', 'Antenna SWR', 'Receiver sensitivity'], 'A', 'Two audio tones produce a steady pattern that shows flat-topping and non-linearity', 'which is useful for diagnosing amplitude linearity and overmodulation issues'),
    ('17.5', 'A spectrum analyser displays a signal in the:', ['Time domain', 'Phase domain only', 'Impedance domain', 'Frequency domain'], 'D', 'The horizontal axis shows the frequencies in the signal', 'shows the signal in its frequency domain'),
    ('17.5', 'Which instrument best shows key clicks, splatter and spurious frequencies?', ['Spectrum analyser', 'Ammeter', 'Dummy load', 'Ohmmeter'], 'A', 'Spurious products appear as extra frequencies on a spectrum analyser', 'It visualises key clicks, splatter, any spurious frequencies'),
    ('17.6', 'A signal generator is used to:', ['Absorb transmitter power', 'Measure resistance', 'Feed test signals into a device under test', 'Display SWR'], 'C', 'Test AF/RF signals are fed in, and the output is compared', 'can generate test signals in the AF and RF ranges'),
    ('17.7', 'When must a dedicated frequency counter be used?', ['Always with modern transceivers', 'With home-built or older equipment, to confirm the transmit frequency', 'Only on VHF', 'Never; it is illegal'], 'B', 'You must know your transmitter is on a legal frequency', 'it is necessary to use a dedicated frequency counter'),
    ('17.8', 'A field strength meter is useful for:', ['Measuring resistance', 'Certifying EMF compliance with a hand-held reading', 'Measuring DC current', 'Checking relative field strength from a directional antenna and finding RF hotspots'], 'D', 'Uncalibrated hand-held meters cannot evaluate EMF compliance', 'is a device useful for checking relative field strength from a directional antenna'),
    ('17.9', 'An antenna analyser combines:', ['A dummy load and an ammeter', 'A wide-range RF oscillator with a reflectometer (SWR meter)', 'A frequency counter and an amplifier', 'A filter and a balun'], 'B', 'It generates test signals and measures SWR, impedance, resistance and reactance', 'which comprises a wide-range oscillator that generates RF test signals'),
    ('17.9', 'A vector network analyser (VNA) is a type of:', ['Transceiver', 'Power supply', 'Dummy load', 'Antenna analyser'], 'D', 'A VNA is a popular type of antenna analyser', 'A popular type of an antenna analyser is a vector network analyser'),
    ('17.10', 'A dummy load is used to:', ['Test a transmitter without radiating a signal', 'Increase antenna gain', 'Measure frequency', 'Receive weak signals'], 'A', 'Connecting a dummy load avoids unwanted emissions during tests', 'the output of a transmitter can be connected to a dummy load'),
    ('17.10', 'A dummy load should present:', ['An open circuit', 'A highly inductive impedance', 'A purely resistive impedance, usually 50 Ω', 'A short circuit'], 'C', 'Known, purely resistive 50 Ω with minimal reactance', 'A dummy load has a known impedance, usually 50'),
    ('17.10', "What happens if a dummy load's power rating is exceeded?", ['It radiates the signal', 'It may overheat, leak or even burn', 'The SWR improves', 'Nothing'], 'B', 'Dummy loads are rated by power and time', 'Exceeding the rating can cause the dummy load to leak or even burn'),
    ('17.10', 'How can a dummy load help find the source of a high SWR?', ['Substitute it for each component in turn, from the transmitter outwards', 'Connect it in parallel with the antenna', 'Use it as an antenna', 'Connect it to the microphone'], 'A', 'If the SWR is normal with the dummy load but high with the component, that component is suspect', 'The dummy load should be connected directly to the transmitter'),
    ('17.1', 'In the circuit shown, which meter is connected as an ammeter?', ['Y', 'Both', 'X', 'Neither'], 'C', 'An ammeter goes in series with the circuit (X); a voltmeter goes across the load (Y)', 'the meter is connected in series with the circuit where the current is to be determined', 'ch17_meters'),
    ('17.1', 'In the circuit shown, meter Y measures:', ['The current through the load', 'The resistance of the battery', 'The power of the battery', 'The voltage across the load'], 'D', 'A meter connected across (in parallel with) a component measures voltage', 'the meter is connected across the points, i.e., in parallel with the circuit', 'ch17_meters'),
    ('17.3', 'What is the peak voltage of the signal shown on the oscilloscope?', ['10 V', '5 V', '2 V', '20 V'], 'A', '2 divisions × 5 V/div = 10 V peak', 'The vertical axis shows the amplitude of the signal', 'ch17_scope'),
    ('17.2', 'The SWR and power meter shows the readings above. How much power is going to the antenna?', ['140 W', '120 W', '20 W', '100 W'], 'D', 'Net power = forward − reflected = 120 − 20 = 100 W', 'the net power going to the antenna is 100 W', 'ch17_swr'),
    ('17.5', 'Which instrument gives a display like the one shown, with frequency on the horizontal axis?', ['Oscilloscope', 'Spectrum analyser', 'Multimeter', 'Frequency counter'], 'B', 'A spectrum analyser shows the signal in the frequency domain, revealing spurious signals', 'shows the signal in its frequency domain', 'ch17_spectrum'),
]
