TITLE = 'Irish Laws, Regulations, and Licence Conditions'
SECTION = 'B.10'
PAGES = (326, 333)
TOPICS = {
    '22.1': 'Wireless Telegraphy Regulations',
    '22.2': 'ComReg Amateur Station Licence Guidelines',
    '22.3': 'Obtaining an Irish Amateur Station Licence',
    '22.4': 'Licence Application, Duration, Amendments, Cancellation, Revocation',
    '22.5': 'Club Licences',
    '22.6': 'Special Events',
    '22.7': 'Land Mobile',
    '22.8': 'Maritime Mobile',
    '22.9': 'Logbook Keeping',
    '22.10': 'Additional Authorisations',
    '22.11': 'Technical Requirements',
    '22.12': 'CE Type Approval',
}

QUESTIONS = [
    ('22.1', 'Which legislation provides for the licensing of amateur radio stations in Ireland?', ['The Wireless Telegraphy (Amateur Station Licence) Regulations 2009', 'The Broadcasting Act', 'The Postal Act', 'The ITU Constitution only'], 'A', 'These regulations also require utmost regard for ComReg guidelines', 'provide for the licensing and the regulation of amateur radio stations in Ireland'),
    ('22.1', 'Who may operate a licensed amateur station?', ['Only the licensee', 'The licensee, or anyone under the direct supervision of the licensee', 'Any member of the public, unsupervised', 'Only other licensed amateurs'], 'B', "Unlicensed persons may operate under the licensee's direct supervision", 'but only under the direct supervision of the licensee'),
    ('22.2', 'ComReg document 09/45 is the:', ['ITU Radio Regulations', 'HAREC syllabus', 'Amateur Station Licence Guidelines', 'CEPT recommendation'], 'C', 'It sets out bands, modes, power limits and technical requirements; you must follow the latest revision', 'Amateur Station Licence Guidelines sets out many of the terms'),
    ('22.2', 'Which revision of the ComReg guidelines must you follow?', ['Only revision R1', 'The one current when you were licensed', 'Any revision', 'The most recent revision available'], 'D', 'You are legally required to know and use the most recent revision', 'You are legally required to know and to use the most recent revision'),
    ('22.2', 'Do the Wireless Telegraphy Regulations exempt you from planning or electrical regulations?', ['No, you must comply with all other applicable laws', 'Yes, fully', 'Only for antennas', 'Only for club stations'], 'A', 'All other statutory requirements still apply', 'do not exempt the licensee from having to comply with any other statutory requirements'),
    ('22.3', 'Which body issues amateur station licences in Ireland?', ['The IRTS', 'ComReg', 'The IARU', 'The Department of Defence'], 'B', 'The Commission for Communications Regulation', 'ComReg issues Amateur Station Licences in Ireland'),
    ('22.3', 'A HAREC holder who provides evidence of Morse qualifications receives:', ['A club licence', 'A CEPT Class 2 licence', 'A novice licence', 'A CEPT Class 1 licence'], 'D', 'Class 1 with Morse; Class 2 without', 'CEPT Class 1 licence if evidence of Morse qualifications is provided'),
    ('22.3', 'How do CEPT Class 1 and Class 2 licences differ in Ireland?', ['Class 2 is limited to 10 W', 'Class 2 has no HF access', 'Only in the type of call sign; rights are the same', 'Class 1 has a shorter lifetime'], 'C', 'Same rights and entitlements; Class 1 call signs are shorter', 'Both licence classes have the same rights and entitlements in Ireland'),
    ('22.4', 'Applications for new or amended amateur station licences are made:', ['Through the ComReg eLicensing website', 'By post to the IRTS', 'At a Garda station', 'By radio'], 'A', 'All applications use www.elicensing.comreg.ie', 'must be made using the ComReg eLicensing website'),
    ('22.4', 'An Irish amateur station licence (other than a temporary assignment) is issued for:', ['1 year', 'The lifetime of the licensee, confirmed every 5 years', '10 years', '5 years, then it expires'], 'B', 'Lifetime licence; confirm the details every 5 years', 'are issued for the lifetime of the licensee'),
    ('22.4', 'After changing your address or contact details, you must inform ComReg within:', ['5 years', '6 months', '7 days', '28 days'], 'D', 'As soon as possible and no later than 28 days', 'no later than 28 days after they have occurred'),
    ('22.4', 'ComReg may suspend or revoke a licence when:', ['The licensee moves house', 'The licensee is inactive for a month', 'There is serious or repeated non-compliance with the licence conditions', 'The licensee changes radio'], 'C', 'Fees are not refunded on cancellation or revocation', 'where there is serious or repeated non-compliance'),
    ('22.5', 'The nominated individual holder of a club licence must:', ['Be over 65', 'Be the club treasurer', 'Hold no other licence', 'Hold a valid amateur station licence in their own name and be responsible for operation'], 'D', 'Rights under a club licence vest in the club, not the individual', 'must also hold a valid Amateur Station Licence in their own name'),
    ('22.6', 'A special event call sign must be applied for at least:', ['One month before the event', 'One day before', 'One year before', 'After the event'], 'A', 'Apply via eLicensing at least a month in advance', 'at least one month before the event'),
    ('22.7', 'A station installed in a land-based vehicle uses the call sign suffix:', ['/MM', '/P', '/M', '/A'], 'C', '/M, spoken "slash mobile", only for stations installed in a land vehicle', 'The call sign must be suffixed by /M'),
    ('22.7', 'The general power limit for land mobile operation in Ireland is:', ['400 W', '50 W (17 dBW)', '10 W', '100 W'], 'B', '50 W, except where a band limit is already lower; 25 W on 70 MHz', 'The power limit is 50 W (17 dBW)'),
    ('22.7', 'A land mobile station may not be established:', ['In a car park', 'On a motorway', 'Within any estuary, dock or harbour, or near an airport', 'In a town'], 'C', 'These locations are excluded for land mobile operation', 'cannot be established within any estuary, dock, or harbour'),
    ('22.7', 'You are operating from a field away from your registered address, not from a vehicle. Your call sign is:', ['Your call sign /P', 'Your call sign without any suffix', 'Your call sign /M', 'Your call sign /MM'], 'B', 'Irish regulations do not permit /P', 'Irish regulations do not permit portable or /P call sign suffixes'),
    ('22.8', 'Before operating as maritime mobile, you need approval from:', ["The ship's master or owner", 'The harbour master only', 'The IRTS', 'The Coast Guard'], 'A', 'Always required, even in a harbour', 'Approval to operate is required from the Ship s Master or owner'),
    ('22.8', 'The maritime mobile call sign suffix is:', ['/AM', '/M', '/P', '/MM'], 'D', '/MM, spoken "slash maritime mobile"', 'The call sign must be suffixed by /MM'),
    ('22.8', 'The power limit for maritime mobile operation is:', ['10 W (10 dBW)', '50 W', '100 W', '400 W'], 'A', '10 W on all permitted bands', 'The power limit on all permitted bands is 10 W'),
    ('22.8', 'Maritime mobile operation is NOT permitted on which band?', ['144 MHz', '14 MHz', '50 MHz', '7 MHz'], 'C', 'Not permitted on 1.8, 5, 10, 50, 70 or 430 MHz', 'Maritime mobile operation is not permitted on the 1.8 MHz'),
    ('22.8', "If an amateur station interferes with a vessel's wireless telegraphy station, you must:", ['Continue if the contact is important', 'Reduce power slightly', 'Change band', 'Stop using the amateur station until the cause is remedied'], 'D', 'Cease operation until fixed', 'use of the amateur station must cease until the cause of the interference has been remedied'),
    ('22.9', 'Which item must be recorded in the station logbook?', ['The name of the other operator', 'The call sign of each station contacted', 'Signal reports', 'QSL card status'], 'B', 'Required: date, UTC times, band, mode, power and stations contacted', 'call sign of the licensed amateur station with which communications have been established'),
    ('22.9', 'Times in the logbook are recorded in:', ['Any time zone', 'Irish local time', 'UTC', 'GPS time'], 'C', 'UTC matches Irish winter time and is one hour behind in summer', 'the times in UTC'),
    ('22.9', 'When must the geographic position be recorded in the logbook?', ['For every contact', 'Only for maritime mobile operation', 'For land mobile only', 'Never'], 'B', 'Only maritime mobile requires the position in the log', 'With the exception of maritime mobile operation, it is no longer required to log the geographic position'),
    ('22.9', 'The logbook must be made available for inspection at the request of:', ['ComReg', 'Any other amateur', 'The IRTS', 'Your neighbours'], 'A', 'ComReg can request to inspect the log', 'made available for inspection at the request of ComReg'),
    ('22.10', 'Which needs a separate formal authorisation from ComReg?', ['Making a contest contact', 'Operating on 20 m SSB', 'Using a new antenna', 'A repeater, beacon or Internet gateway'], 'D', 'Automatic or remote station licences, and extra bands or power for experiments', 'automatic or remote station licence, for example, a repeater, beacon'),
    ('22.11', 'Licence conditions require you to have a device capable of measuring:', ['SWR', 'Field strength', 'Capacitance', 'Temperature'], 'A', 'You must have an SWR measuring device and an accurate frequency indication', 'The licensee must have a device capable of measuring SWR'),
    ('22.11', 'For home-constructed equipment, the transmit frequency can be checked with:', ['An SWR meter', 'A frequency counter or synthesised receiver', 'A dummy load', 'An ohmmeter'], 'B', 'You must have an accurate way to ensure you are on the correct frequency', 'a frequency counter or synthesised main receiver'),
    ('22.12', 'Radio transmitting equipment sold to the public in the EU must display:', ['The ITU logo', 'The IRTS logo', 'The CE mark', 'A call sign'], 'C', 'The CE mark shows compliance with the RED and EMC directives', 'must display CE marking'),
    ('22.12', 'May a licensed amateur build and use equipment without the CE mark?', ['Only on VHF', 'No, never', 'Only below 1 W', 'Yes, accepting responsibility for its safety and regulatory compliance'], 'D', 'The EU directive excludes amateur-built and kit equipment', 'you are allowed to build your own and to use equipment that does not have the CE mark'),
]
