TITLE = 'Operating Procedures and Non-Interference'
SECTION = 'B.7'
PAGES = (360, 371)
TOPICS = {
    '29.1': 'How to Make a QSO',
    '29.2': 'Content of Transmissions',
    '29.3.1': 'Selecting a Frequency',
    '29.3.2': 'Format of CQ Calls',
    '29.3.5': 'Initial Call to a Specific Station',
    '29.4': 'Replying to Initial Calls',
    '29.5': 'RST Code',
    '29.6': 'Non-Interference',
    '29.6.1': 'How to Deal with Spectrum Interference?',
}

QUESTIONS = [
    ('29.1', 'EI5ABC wants to address W1ZZZ on phone. The correct order of call signs is:', ['EI5ABC from W1ZZZ', 'W1ZZZ from EI5ABC', 'EI5ABC W1ZZZ', 'Either order'], 'B', 'The station called comes first, your own call second', 'You always start with the call sign of the person you speak to'),
    ('29.1', 'In Morse, EI5ABC calling W1ZZZ sends:', ['W1ZZZ DE EI5ABC', 'EI5ABC DE W1ZZZ', 'W1ZZZ EI5ABC CQ', 'DE W1ZZZ EI5ABC'], 'A', 'DE separates the two call signs', ('W1ZZZ DE EI5ABC', 360, 360)),
    ('29.1', 'A QSO consists of a series of:', ['Beacon signals', 'Simultaneous transmissions', 'Overs, with one station transmitting at a time', 'Broadcasts'], 'C', 'One person speaks while the other listens (simplex)', 'it consists of a series of overs'),
    ('29.1', 'When the other station hands over to you, it is good practice to:', ['Change frequency', 'Start immediately', 'Call CQ', 'Wait a brief second before transmitting'], 'D', 'This lets anyone trying to join or use the frequency be heard', 'wait a brief second before starting your transmission'),
    ('29.1', 'Should transmissions in a QSO be short or long?', ['Preferably short', 'As long as possible', 'Exactly 5 minutes', 'It does not matter'], 'A', 'Short overs let your correspondent comment', 'Preferably make short rather than long transmissions'),
    ('29.2', 'Which subject should be avoided on air according to the IARU guide?', ['Antennas', 'Politics', 'Propagation', 'The weather'], 'B', 'Avoid religion, politics, business, derogatory remarks and bathroom humour', 'politics'),
    ('29.2', 'May you advertise your business on amateur radio?', ['Only on VHF', 'Yes, on weekdays', 'No', 'Only to friends'], 'C', 'You may talk about your profession but not advertise', 'but you cannot advertise for your business'),
    ('29.2', 'Broadcasting music to a general audience on amateur bands is:', ['Encouraged', 'Permitted at low power', 'Permitted at weekends', 'Not permitted'], 'D', 'Radio amateurs may not broadcast to a potentially unknown audience', 'Radio amateurs are not permitted to broadcast'),
    ('29.3.1', 'Before calling CQ on an apparently clear frequency, on phone you should ask:', ['Is this frequency clear?', 'Is this frequency in use?', 'Can anyone hear me?', 'Nothing; just call'], 'B', '"Clear" is ambiguous; ask if it is in use, more than once', 'Is this frequency in use from EI5ABC'),
    ('29.3.1', 'In Morse, to check whether a frequency is in use, send:', ['QTH?', 'QRZ?', 'QRL?', 'QSY?'], 'C', 'QRL? DE EI5ABC', ('QRL? DE EI5ABC', 362, 362)),
    ('29.3.1', 'Why ask if a frequency is in use even if you hear nothing?', ['A station you cannot hear may be receiving a station you cannot hear either', 'It is a contest rule', 'To test your microphone', 'To check SWR'], 'A', 'You might cause QRM to a station in your propagation path', 'One station, part of a QSO, may be in a location that you cannot hear'),
    ('29.3.1', 'You are in a QSO and hear QRL? in Morse. You can reply:', ['Nothing', 'QRZ?', 'CQ', 'QRL, R, Y, YES or C'], 'D', 'Confirm the frequency is in use', 'QRL, R, Y, YES, C'),
    ('29.3.2', 'The recommended CQ call format in Morse is:', ['EI5ABC CQ CQ CQ', 'CQ CQ CQ DE EI5ABC EI5ABC EI5ABC K', 'CQ DE EI5ABC KN', 'CQ CQ CQ EI5ABC SK'], 'B', 'K at the end invites any station to transmit', 'CQ CQ CQ DE EI5ABC EI5ABC EI5ABC K'),
    ('29.3.2', 'The final K of a CQ call is known as:', ['Kilohertz', 'End of contact', 'An invitation to transmit', 'A distress signal'], 'C', 'K invites any station to transmit', 'is known as an invitation to transmit'),
    ('29.3.2', 'You only want to work stations in Japan. In Morse, you call:', ['CQ JA CQ JA CQ JA DE EI5ABC …', 'CQ DX JAPAN', 'JA DE EI5ABC KN', 'QRZ JA?'], 'A', 'JA is the national prefix for Japan', 'Because JA is the national prefix for Japan'),
    ('29.3.2', 'On VHF/UHF, a CQ DX call seeks stations more than about:', ['3 km away', '30 km away', '3000 km away', '300 km away'], 'D', 'On HF, DX usually means another continent', 'stations located more than 300 km away'),
    ('29.3.2', 'Should you reply to a CQ DX call from a station on your own continent?', ['Yes, always', 'No, unless you are DX to that station', 'Only with high power', 'Only on CW'], 'B', 'Only answer CQ DX if you are DX for the caller', 'do not reply to CQ DX unless you are DX to that station'),
    ('29.3.5', 'Ending a call to a specific station with KN in Morse means:', ['Change frequency', 'Any station may reply', 'End of contact', 'Only the called station should reply'], 'D', 'K alone allows others to join', 'indicates that you do not want any other stations to call you'),
    ('29.3.5', 'A call to a station you have arranged to meet should not use:', ['CQ, since it is not a general call', 'Your call sign', "The other station's call sign", 'DE'], 'A', 'It is a call only to that station, e.g. on a sked', 'It would be inappropriate to call CQ in this case'),
    ('29.4', "EI6XYZ answers EI5ABC's Morse CQ. A correct reply is:", ['CQ DE EI6XYZ', 'EI6XYZ DE EI5ABC K', 'EI5ABC DE EI6XYZ KN', 'QRZ? DE EI6XYZ'], 'C', 'Their call first (optional), then DE and your call', ('EI5ABC DE EI6XYZ KN', 366, 366)),
    ('29.4', 'When answering a CQ, what must you always do?', ['Identify yourself', 'Send your full address', 'Repeat your call sign 10 times', 'Give a 599 report'], 'A', 'It is not always necessary to send their call, but you must identify', 'It is, however, vital that you always identify yourself at this stage of a QSO'),
    ('29.5', 'In an RST report, R stands for:', ['Resistance', 'Range', 'Readability', 'Reflection'], 'C', 'R = readability, S = signal strength, T = tone', 'This is an assessment of how hard or easy it is to correctly copy'),
    ('29.5', 'R5 means:', ['Readable with considerable difficulty', 'Unreadable', 'Barely readable', 'Perfectly readable'], 'D', 'R1 unreadable … R5 perfectly readable', 'Perfectly readable'),
    ('29.5', 'R3 means:', ['Perfectly readable', 'Readable with considerable difficulty', 'Unreadable', 'Readable with practically no difficulty'], 'B', 'R3: readable with considerable difficulty', 'Readable with considerable difficulty'),
    ('29.5', 'R2 means:', ['Barely readable, occasional words distinguishable', 'Unreadable', 'Readable with practically no difficulty', 'Perfectly readable'], 'A', 'R2: barely readable', 'Barely readable, occasional words distinguishable'),
    ('29.5', 'R4 means:', ['Barely readable', 'Readable with considerable difficulty', 'Perfectly readable', 'Readable with practically no difficulty'], 'D', 'R4: practically no difficulty', 'Readable with practically no difficulty'),
    ('29.5', 'The S in an RST report should be taken from:', ['The SWR meter', "The receiver's S meter", 'The transmitter power', 'A guess'], 'B', 'Report the S-meter reading, e.g. 59+10', 'You should report the number shown on your receiver s S meter'),
    ('29.5', 'In a CW report, a T value other than 9 indicates:', ['Perfect readability', 'A very strong signal', 'A problem with the quality of the transmitted tone', 'QSB'], 'C', 'Modern transmitters should always give T9', 'anything other than T9 indicates a problem with the quality of the tone'),
    ('29.5', 'The T (tone) part of RST is used in:', ['Morse code and digital transmissions only', 'SSB only', 'FM only', 'All voice modes'], 'A', 'Voice reports use only R and S, e.g. 59', 'Used only in Morse code and digital transmissions'),
    ('29.5', 'A report of 339 in Morse means:', ['Readable, fair signals, rough tone', 'Perfectly readable, strong signals', 'Unreadable', 'Readable with considerable difficulty, weak signals, perfect tone'], 'D', 'R3, S3, T9', 'readable with considerable difficulty, weak signals, perfect tone'),
    ('29.5', 'A phone report of "59 plus 10" means:', ['Weak signal', 'Readability 5, strength 9, tone 10', 'Perfectly readable, S-meter 10 dB above S9', 'Readable with difficulty'], 'C', 'Signals above S9 are reported in dB over 9', 'you should use a phrase such as 59+10'),
    ('29.6', 'Who is legally responsible for ensuring your equipment does not cause interference to other spectrum users?', ['The manufacturer', 'You, the licensee', 'The seller', 'ComReg'], 'B', 'The licensee, not the manufacturer or seller, is responsible', 'it is you, and not the manufacturer or the seller'),
    ('29.6', 'On a band where amateurs are secondary users, if a primary (non-amateur) user starts transmitting you must:', ['Increase power', 'Continue your QSO', 'Stop using the frequency', 'Ask them to QSY'], 'C', 'Secondary users must not interfere with primary users', 'Stop using it if a non-amateur starts transmitting'),
    ('29.6.1', 'Deliberate interference to the amateur bands should first be reported to:', ['Nobody', 'The police', 'The interfering station', 'The IRTS (national IARU society), for the IARU Monitoring System'], 'D', 'IARUMS R1 recommends reporting through the national society first', 'IARUMS recommends that you first report them to the national IARU society'),
    ('29.6.1', 'Harmful interference from an individual that cannot be resolved after informing them should be reported to:', ['The ITU', 'ComReg', 'CEPT', 'The local radio club'], 'B', 'ComReg is the correct authority; the IRTS can advise', 'the correct authority to report this matter to is ComReg'),
]
